/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ProjectDatabaseServerTimezone implements EnumType {

    Africa_2fAbidjan("Africa/Abidjan"),

    Africa_2fAccra("Africa/Accra"),

    Africa_2fAddis_Ababa("Africa/Addis_Ababa"),

    Africa_2fAlgiers("Africa/Algiers"),

    Africa_2fAsmara("Africa/Asmara"),

    Africa_2fAsmera("Africa/Asmera"),

    Africa_2fBamako("Africa/Bamako"),

    Africa_2fBangui("Africa/Bangui"),

    Africa_2fBanjul("Africa/Banjul"),

    Africa_2fBissau("Africa/Bissau"),

    Africa_2fBlantyre("Africa/Blantyre"),

    Africa_2fBrazzaville("Africa/Brazzaville"),

    Africa_2fBujumbura("Africa/Bujumbura"),

    Africa_2fCairo("Africa/Cairo"),

    Africa_2fCasablanca("Africa/Casablanca"),

    Africa_2fCeuta("Africa/Ceuta"),

    Africa_2fConakry("Africa/Conakry"),

    Africa_2fDakar("Africa/Dakar"),

    Africa_2fDar_es_Salaam("Africa/Dar_es_Salaam"),

    Africa_2fDjibouti("Africa/Djibouti"),

    Africa_2fDouala("Africa/Douala"),

    Africa_2fEl_Aaiun("Africa/El_Aaiun"),

    Africa_2fFreetown("Africa/Freetown"),

    Africa_2fGaborone("Africa/Gaborone"),

    Africa_2fHarare("Africa/Harare"),

    Africa_2fJohannesburg("Africa/Johannesburg"),

    Africa_2fJuba("Africa/Juba"),

    Africa_2fKampala("Africa/Kampala"),

    Africa_2fKhartoum("Africa/Khartoum"),

    Africa_2fKigali("Africa/Kigali"),

    Africa_2fKinshasa("Africa/Kinshasa"),

    Africa_2fLagos("Africa/Lagos"),

    Africa_2fLibreville("Africa/Libreville"),

    Africa_2fLome("Africa/Lome"),

    Africa_2fLuanda("Africa/Luanda"),

    Africa_2fLubumbashi("Africa/Lubumbashi"),

    Africa_2fLusaka("Africa/Lusaka"),

    Africa_2fMalabo("Africa/Malabo"),

    Africa_2fMaputo("Africa/Maputo"),

    Africa_2fMaseru("Africa/Maseru"),

    Africa_2fMbabane("Africa/Mbabane"),

    Africa_2fMogadishu("Africa/Mogadishu"),

    Africa_2fMonrovia("Africa/Monrovia"),

    Africa_2fNairobi("Africa/Nairobi"),

    Africa_2fNdjamena("Africa/Ndjamena"),

    Africa_2fNiamey("Africa/Niamey"),

    Africa_2fNouakchott("Africa/Nouakchott"),

    Africa_2fOuagadougou("Africa/Ouagadougou"),

    Africa_2fPorto_Novo("Africa/Porto-Novo"),

    Africa_2fSao_Tome("Africa/Sao_Tome"),

    Africa_2fTimbuktu("Africa/Timbuktu"),

    Africa_2fTripoli("Africa/Tripoli"),

    Africa_2fTunis("Africa/Tunis"),

    Africa_2fWindhoek("Africa/Windhoek"),

    America_2fAdak("America/Adak"),

    America_2fAnchorage("America/Anchorage"),

    America_2fAnguilla("America/Anguilla"),

    America_2fAntigua("America/Antigua"),

    America_2fAraguaina("America/Araguaina"),

    America_2fArgentina_2fBuenos_Aires("America/Argentina/Buenos_Aires"),

    America_2fArgentina_2fCatamarca("America/Argentina/Catamarca"),

    America_2fArgentina_2fComodRivadavia("America/Argentina/ComodRivadavia"),

    America_2fArgentina_2fCordoba("America/Argentina/Cordoba"),

    America_2fArgentina_2fJujuy("America/Argentina/Jujuy"),

    America_2fArgentina_2fLa_Rioja("America/Argentina/La_Rioja"),

    America_2fArgentina_2fMendoza("America/Argentina/Mendoza"),

    America_2fArgentina_2fRio_Gallegos("America/Argentina/Rio_Gallegos"),

    America_2fArgentina_2fSalta("America/Argentina/Salta"),

    America_2fArgentina_2fSan_Juan("America/Argentina/San_Juan"),

    America_2fArgentina_2fSan_Luis("America/Argentina/San_Luis"),

    America_2fArgentina_2fTucuman("America/Argentina/Tucuman"),

    America_2fArgentina_2fUshuaia("America/Argentina/Ushuaia"),

    America_2fAruba("America/Aruba"),

    America_2fAsuncion("America/Asuncion"),

    America_2fAtikokan("America/Atikokan"),

    America_2fAtka("America/Atka"),

    America_2fBahia("America/Bahia"),

    America_2fBahia_Banderas("America/Bahia_Banderas"),

    America_2fBarbados("America/Barbados"),

    America_2fBelem("America/Belem"),

    America_2fBelize("America/Belize"),

    America_2fBlanc_Sablon("America/Blanc-Sablon"),

    America_2fBoa_Vista("America/Boa_Vista"),

    America_2fBogota("America/Bogota"),

    America_2fBoise("America/Boise"),

    America_2fBuenos_Aires("America/Buenos_Aires"),

    America_2fCambridge_Bay("America/Cambridge_Bay"),

    America_2fCampo_Grande("America/Campo_Grande"),

    America_2fCancun("America/Cancun"),

    America_2fCaracas("America/Caracas"),

    America_2fCatamarca("America/Catamarca"),

    America_2fCayenne("America/Cayenne"),

    America_2fCayman("America/Cayman"),

    America_2fChicago("America/Chicago"),

    America_2fChihuahua("America/Chihuahua"),

    America_2fCoral_Harbour("America/Coral_Harbour"),

    America_2fCordoba("America/Cordoba"),

    America_2fCosta_Rica("America/Costa_Rica"),

    America_2fCreston("America/Creston"),

    America_2fCuiaba("America/Cuiaba"),

    America_2fCuracao("America/Curacao"),

    America_2fDanmarkshavn("America/Danmarkshavn"),

    America_2fDawson("America/Dawson"),

    America_2fDawson_Creek("America/Dawson_Creek"),

    America_2fDenver("America/Denver"),

    America_2fDetroit("America/Detroit"),

    America_2fDominica("America/Dominica"),

    America_2fEdmonton("America/Edmonton"),

    America_2fEirunepe("America/Eirunepe"),

    America_2fEl_Salvador("America/El_Salvador"),

    America_2fEnsenada("America/Ensenada"),

    America_2fFort_Nelson("America/Fort_Nelson"),

    America_2fFort_Wayne("America/Fort_Wayne"),

    America_2fFortaleza("America/Fortaleza"),

    America_2fGlace_Bay("America/Glace_Bay"),

    America_2fGodthab("America/Godthab"),

    America_2fGoose_Bay("America/Goose_Bay"),

    America_2fGrand_Turk("America/Grand_Turk"),

    America_2fGrenada("America/Grenada"),

    America_2fGuadeloupe("America/Guadeloupe"),

    America_2fGuatemala("America/Guatemala"),

    America_2fGuayaquil("America/Guayaquil"),

    America_2fGuyana("America/Guyana"),

    America_2fHalifax("America/Halifax"),

    America_2fHavana("America/Havana"),

    America_2fHermosillo("America/Hermosillo"),

    America_2fIndiana_2fIndianapolis("America/Indiana/Indianapolis"),

    America_2fIndiana_2fKnox("America/Indiana/Knox"),

    America_2fIndiana_2fMarengo("America/Indiana/Marengo"),

    America_2fIndiana_2fPetersburg("America/Indiana/Petersburg"),

    America_2fIndiana_2fTell_City("America/Indiana/Tell_City"),

    America_2fIndiana_2fVevay("America/Indiana/Vevay"),

    America_2fIndiana_2fVincennes("America/Indiana/Vincennes"),

    America_2fIndiana_2fWinamac("America/Indiana/Winamac"),

    America_2fIndianapolis("America/Indianapolis"),

    America_2fInuvik("America/Inuvik"),

    America_2fIqaluit("America/Iqaluit"),

    America_2fJamaica("America/Jamaica"),

    America_2fJujuy("America/Jujuy"),

    America_2fJuneau("America/Juneau"),

    America_2fKentucky_2fLouisville("America/Kentucky/Louisville"),

    America_2fKentucky_2fMonticello("America/Kentucky/Monticello"),

    America_2fKnox_IN("America/Knox_IN"),

    America_2fKralendijk("America/Kralendijk"),

    America_2fLa_Paz("America/La_Paz"),

    America_2fLima("America/Lima"),

    America_2fLos_Angeles("America/Los_Angeles"),

    America_2fLouisville("America/Louisville"),

    America_2fLower_Princes("America/Lower_Princes"),

    America_2fMaceio("America/Maceio"),

    America_2fManagua("America/Managua"),

    America_2fManaus("America/Manaus"),

    America_2fMarigot("America/Marigot"),

    America_2fMartinique("America/Martinique"),

    America_2fMatamoros("America/Matamoros"),

    America_2fMazatlan("America/Mazatlan"),

    America_2fMendoza("America/Mendoza"),

    America_2fMenominee("America/Menominee"),

    America_2fMerida("America/Merida"),

    America_2fMetlakatla("America/Metlakatla"),

    America_2fMexico_City("America/Mexico_City"),

    America_2fMiquelon("America/Miquelon"),

    America_2fMoncton("America/Moncton"),

    America_2fMonterrey("America/Monterrey"),

    America_2fMontevideo("America/Montevideo"),

    America_2fMontreal("America/Montreal"),

    America_2fMontserrat("America/Montserrat"),

    America_2fNassau("America/Nassau"),

    America_2fNew_York("America/New_York"),

    America_2fNipigon("America/Nipigon"),

    America_2fNome("America/Nome"),

    America_2fNoronha("America/Noronha"),

    America_2fNorth_Dakota_2fBeulah("America/North_Dakota/Beulah"),

    America_2fNorth_Dakota_2fCenter("America/North_Dakota/Center"),

    America_2fNorth_Dakota_2fNew_Salem("America/North_Dakota/New_Salem"),

    America_2fOjinaga("America/Ojinaga"),

    America_2fPanama("America/Panama"),

    America_2fPangnirtung("America/Pangnirtung"),

    America_2fParamaribo("America/Paramaribo"),

    America_2fPhoenix("America/Phoenix"),

    America_2fPort_au_Prince("America/Port-au-Prince"),

    America_2fPort_of_Spain("America/Port_of_Spain"),

    America_2fPorto_Acre("America/Porto_Acre"),

    America_2fPorto_Velho("America/Porto_Velho"),

    America_2fPuerto_Rico("America/Puerto_Rico"),

    America_2fPunta_Arenas("America/Punta_Arenas"),

    America_2fRainy_River("America/Rainy_River"),

    America_2fRankin_Inlet("America/Rankin_Inlet"),

    America_2fRecife("America/Recife"),

    America_2fRegina("America/Regina"),

    America_2fResolute("America/Resolute"),

    America_2fRio_Branco("America/Rio_Branco"),

    America_2fRosario("America/Rosario"),

    America_2fSanta_Isabel("America/Santa_Isabel"),

    America_2fSantarem("America/Santarem"),

    America_2fSantiago("America/Santiago"),

    America_2fSanto_Domingo("America/Santo_Domingo"),

    America_2fSao_Paulo("America/Sao_Paulo"),

    America_2fScoresbysund("America/Scoresbysund"),

    America_2fShiprock("America/Shiprock"),

    America_2fSitka("America/Sitka"),

    America_2fSt_Barthelemy("America/St_Barthelemy"),

    America_2fSt_Johns("America/St_Johns"),

    America_2fSt_Kitts("America/St_Kitts"),

    America_2fSt_Lucia("America/St_Lucia"),

    America_2fSt_Thomas("America/St_Thomas"),

    America_2fSt_Vincent("America/St_Vincent"),

    America_2fSwift_Current("America/Swift_Current"),

    America_2fTegucigalpa("America/Tegucigalpa"),

    America_2fThule("America/Thule"),

    America_2fThunder_Bay("America/Thunder_Bay"),

    America_2fTijuana("America/Tijuana"),

    America_2fToronto("America/Toronto"),

    America_2fTortola("America/Tortola"),

    America_2fVancouver("America/Vancouver"),

    America_2fVirgin("America/Virgin"),

    America_2fWhitehorse("America/Whitehorse"),

    America_2fWinnipeg("America/Winnipeg"),

    America_2fYakutat("America/Yakutat"),

    America_2fYellowknife("America/Yellowknife"),

    Antarctica_2fCasey("Antarctica/Casey"),

    Antarctica_2fDavis("Antarctica/Davis"),

    Antarctica_2fDumontDUrville("Antarctica/DumontDUrville"),

    Antarctica_2fMacquarie("Antarctica/Macquarie"),

    Antarctica_2fMawson("Antarctica/Mawson"),

    Antarctica_2fMcMurdo("Antarctica/McMurdo"),

    Antarctica_2fPalmer("Antarctica/Palmer"),

    Antarctica_2fRothera("Antarctica/Rothera"),

    Antarctica_2fSouth_Pole("Antarctica/South_Pole"),

    Antarctica_2fSyowa("Antarctica/Syowa"),

    Antarctica_2fTroll("Antarctica/Troll"),

    Antarctica_2fVostok("Antarctica/Vostok"),

    Arctic_2fLongyearbyen("Arctic/Longyearbyen"),

    Asia_2fAden("Asia/Aden"),

    Asia_2fAlmaty("Asia/Almaty"),

    Asia_2fAmman("Asia/Amman"),

    Asia_2fAnadyr("Asia/Anadyr"),

    Asia_2fAqtau("Asia/Aqtau"),

    Asia_2fAqtobe("Asia/Aqtobe"),

    Asia_2fAshgabat("Asia/Ashgabat"),

    Asia_2fAshkhabad("Asia/Ashkhabad"),

    Asia_2fAtyrau("Asia/Atyrau"),

    Asia_2fBaghdad("Asia/Baghdad"),

    Asia_2fBahrain("Asia/Bahrain"),

    Asia_2fBaku("Asia/Baku"),

    Asia_2fBangkok("Asia/Bangkok"),

    Asia_2fBarnaul("Asia/Barnaul"),

    Asia_2fBeirut("Asia/Beirut"),

    Asia_2fBishkek("Asia/Bishkek"),

    Asia_2fBrunei("Asia/Brunei"),

    Asia_2fCalcutta("Asia/Calcutta"),

    Asia_2fChita("Asia/Chita"),

    Asia_2fChoibalsan("Asia/Choibalsan"),

    Asia_2fChongqing("Asia/Chongqing"),

    Asia_2fChungking("Asia/Chungking"),

    Asia_2fColombo("Asia/Colombo"),

    Asia_2fDacca("Asia/Dacca"),

    Asia_2fDamascus("Asia/Damascus"),

    Asia_2fDhaka("Asia/Dhaka"),

    Asia_2fDili("Asia/Dili"),

    Asia_2fDubai("Asia/Dubai"),

    Asia_2fDushanbe("Asia/Dushanbe"),

    Asia_2fFamagusta("Asia/Famagusta"),

    Asia_2fGaza("Asia/Gaza"),

    Asia_2fHarbin("Asia/Harbin"),

    Asia_2fHebron("Asia/Hebron"),

    Asia_2fHo_Chi_Minh("Asia/Ho_Chi_Minh"),

    Asia_2fHong_Kong("Asia/Hong_Kong"),

    Asia_2fHovd("Asia/Hovd"),

    Asia_2fIrkutsk("Asia/Irkutsk"),

    Asia_2fIstanbul("Asia/Istanbul"),

    Asia_2fJakarta("Asia/Jakarta"),

    Asia_2fJayapura("Asia/Jayapura"),

    Asia_2fJerusalem("Asia/Jerusalem"),

    Asia_2fKabul("Asia/Kabul"),

    Asia_2fKamchatka("Asia/Kamchatka"),

    Asia_2fKarachi("Asia/Karachi"),

    Asia_2fKashgar("Asia/Kashgar"),

    Asia_2fKathmandu("Asia/Kathmandu"),

    Asia_2fKatmandu("Asia/Katmandu"),

    Asia_2fKhandyga("Asia/Khandyga"),

    Asia_2fKolkata("Asia/Kolkata"),

    Asia_2fKrasnoyarsk("Asia/Krasnoyarsk"),

    Asia_2fKuala_Lumpur("Asia/Kuala_Lumpur"),

    Asia_2fKuching("Asia/Kuching"),

    Asia_2fKuwait("Asia/Kuwait"),

    Asia_2fMacao("Asia/Macao"),

    Asia_2fMacau("Asia/Macau"),

    Asia_2fMagadan("Asia/Magadan"),

    Asia_2fMakassar("Asia/Makassar"),

    Asia_2fManila("Asia/Manila"),

    Asia_2fMuscat("Asia/Muscat"),

    Asia_2fNicosia("Asia/Nicosia"),

    Asia_2fNovokuznetsk("Asia/Novokuznetsk"),

    Asia_2fNovosibirsk("Asia/Novosibirsk"),

    Asia_2fOmsk("Asia/Omsk"),

    Asia_2fOral("Asia/Oral"),

    Asia_2fPhnom_Penh("Asia/Phnom_Penh"),

    Asia_2fPontianak("Asia/Pontianak"),

    Asia_2fPyongyang("Asia/Pyongyang"),

    Asia_2fQatar("Asia/Qatar"),

    Asia_2fQostanay("Asia/Qostanay"),

    Asia_2fQyzylorda("Asia/Qyzylorda"),

    Asia_2fRangoon("Asia/Rangoon"),

    Asia_2fRiyadh("Asia/Riyadh"),

    Asia_2fSaigon("Asia/Saigon"),

    Asia_2fSakhalin("Asia/Sakhalin"),

    Asia_2fSamarkand("Asia/Samarkand"),

    Asia_2fSeoul("Asia/Seoul"),

    Asia_2fShanghai("Asia/Shanghai"),

    Asia_2fSingapore("Asia/Singapore"),

    Asia_2fSrednekolymsk("Asia/Srednekolymsk"),

    Asia_2fTaipei("Asia/Taipei"),

    Asia_2fTashkent("Asia/Tashkent"),

    Asia_2fTbilisi("Asia/Tbilisi"),

    Asia_2fTehran("Asia/Tehran"),

    Asia_2fTel_Aviv("Asia/Tel_Aviv"),

    Asia_2fThimbu("Asia/Thimbu"),

    Asia_2fThimphu("Asia/Thimphu"),

    Asia_2fTokyo("Asia/Tokyo"),

    Asia_2fTomsk("Asia/Tomsk"),

    Asia_2fUjung_Pandang("Asia/Ujung_Pandang"),

    Asia_2fUlaanbaatar("Asia/Ulaanbaatar"),

    Asia_2fUlan_Bator("Asia/Ulan_Bator"),

    Asia_2fUrumqi("Asia/Urumqi"),

    Asia_2fUst_Nera("Asia/Ust-Nera"),

    Asia_2fVientiane("Asia/Vientiane"),

    Asia_2fVladivostok("Asia/Vladivostok"),

    Asia_2fYakutsk("Asia/Yakutsk"),

    Asia_2fYangon("Asia/Yangon"),

    Asia_2fYekaterinburg("Asia/Yekaterinburg"),

    Asia_2fYerevan("Asia/Yerevan"),

    Atlantic_2fAzores("Atlantic/Azores"),

    Atlantic_2fBermuda("Atlantic/Bermuda"),

    Atlantic_2fCanary("Atlantic/Canary"),

    Atlantic_2fCape_Verde("Atlantic/Cape_Verde"),

    Atlantic_2fFaeroe("Atlantic/Faeroe"),

    Atlantic_2fFaroe("Atlantic/Faroe"),

    Atlantic_2fJan_Mayen("Atlantic/Jan_Mayen"),

    Atlantic_2fMadeira("Atlantic/Madeira"),

    Atlantic_2fReykjavik("Atlantic/Reykjavik"),

    Atlantic_2fSouth_Georgia("Atlantic/South_Georgia"),

    Atlantic_2fSt_Helena("Atlantic/St_Helena"),

    Atlantic_2fStanley("Atlantic/Stanley"),

    Australia_2fACT("Australia/ACT"),

    Australia_2fAdelaide("Australia/Adelaide"),

    Australia_2fBrisbane("Australia/Brisbane"),

    Australia_2fBroken_Hill("Australia/Broken_Hill"),

    Australia_2fCanberra("Australia/Canberra"),

    Australia_2fCurrie("Australia/Currie"),

    Australia_2fDarwin("Australia/Darwin"),

    Australia_2fEucla("Australia/Eucla"),

    Australia_2fHobart("Australia/Hobart"),

    Australia_2fLHI("Australia/LHI"),

    Australia_2fLindeman("Australia/Lindeman"),

    Australia_2fLord_Howe("Australia/Lord_Howe"),

    Australia_2fMelbourne("Australia/Melbourne"),

    Australia_2fNorth("Australia/North"),

    Australia_2fNSW("Australia/NSW"),

    Australia_2fPerth("Australia/Perth"),

    Australia_2fQueensland("Australia/Queensland"),

    Australia_2fSouth("Australia/South"),

    Australia_2fSydney("Australia/Sydney"),

    Australia_2fTasmania("Australia/Tasmania"),

    Australia_2fVictoria("Australia/Victoria"),

    Australia_2fWest("Australia/West"),

    Australia_2fYancowinna("Australia/Yancowinna"),

    Brazil_2fAcre("Brazil/Acre"),

    Brazil_2fDeNoronha("Brazil/DeNoronha"),

    Brazil_2fEast("Brazil/East"),

    Brazil_2fWest("Brazil/West"),

    Canada_2fAtlantic("Canada/Atlantic"),

    Canada_2fCentral("Canada/Central"),

    Canada_2fEastern("Canada/Eastern"),

    Canada_2fMountain("Canada/Mountain"),

    Canada_2fNewfoundland("Canada/Newfoundland"),

    Canada_2fPacific("Canada/Pacific"),

    Canada_2fSaskatchewan("Canada/Saskatchewan"),

    Canada_2fYukon("Canada/Yukon"),

    Chile_2fContinental("Chile/Continental"),

    Chile_2fEasterIsland("Chile/EasterIsland"),

    Etc_2fGMT("Etc/GMT"),

    Etc_2fGMT_2b0("Etc/GMT+0"),

    Etc_2fGMT_2b1("Etc/GMT+1"),

    Etc_2fGMT_2b10("Etc/GMT+10"),

    Etc_2fGMT_2b11("Etc/GMT+11"),

    Etc_2fGMT_2b12("Etc/GMT+12"),

    Etc_2fGMT_2b2("Etc/GMT+2"),

    Etc_2fGMT_2b3("Etc/GMT+3"),

    Etc_2fGMT_2b4("Etc/GMT+4"),

    Etc_2fGMT_2b5("Etc/GMT+5"),

    Etc_2fGMT_2b6("Etc/GMT+6"),

    Etc_2fGMT_2b7("Etc/GMT+7"),

    Etc_2fGMT_2b8("Etc/GMT+8"),

    Etc_2fGMT_2b9("Etc/GMT+9"),

    Etc_2fGMT_0("Etc/GMT-0"),

    Etc_2fGMT_1("Etc/GMT-1"),

    Etc_2fGMT_10("Etc/GMT-10"),

    Etc_2fGMT_11("Etc/GMT-11"),

    Etc_2fGMT_12("Etc/GMT-12"),

    Etc_2fGMT_13("Etc/GMT-13"),

    Etc_2fGMT_14("Etc/GMT-14"),

    Etc_2fGMT_2("Etc/GMT-2"),

    Etc_2fGMT_3("Etc/GMT-3"),

    Etc_2fGMT_4("Etc/GMT-4"),

    Etc_2fGMT_5("Etc/GMT-5"),

    Etc_2fGMT_6("Etc/GMT-6"),

    Etc_2fGMT_7("Etc/GMT-7"),

    Etc_2fGMT_8("Etc/GMT-8"),

    Etc_2fGMT_9("Etc/GMT-9"),

    Etc_2fGMT0("Etc/GMT0"),

    Etc_2fGreenwich("Etc/Greenwich"),

    Etc_2fUCT("Etc/UCT"),

    Etc_2fUniversal("Etc/Universal"),

    Etc_2fUTC("Etc/UTC"),

    Etc_2fZulu("Etc/Zulu"),

    Europe_2fAmsterdam("Europe/Amsterdam"),

    Europe_2fAndorra("Europe/Andorra"),

    Europe_2fAstrakhan("Europe/Astrakhan"),

    Europe_2fAthens("Europe/Athens"),

    Europe_2fBelfast("Europe/Belfast"),

    Europe_2fBelgrade("Europe/Belgrade"),

    Europe_2fBerlin("Europe/Berlin"),

    Europe_2fBratislava("Europe/Bratislava"),

    Europe_2fBrussels("Europe/Brussels"),

    Europe_2fBucharest("Europe/Bucharest"),

    Europe_2fBudapest("Europe/Budapest"),

    Europe_2fBusingen("Europe/Busingen"),

    Europe_2fChisinau("Europe/Chisinau"),

    Europe_2fCopenhagen("Europe/Copenhagen"),

    Europe_2fDublin("Europe/Dublin"),

    Europe_2fGibraltar("Europe/Gibraltar"),

    Europe_2fGuernsey("Europe/Guernsey"),

    Europe_2fHelsinki("Europe/Helsinki"),

    Europe_2fIsle_of_Man("Europe/Isle_of_Man"),

    Europe_2fIstanbul("Europe/Istanbul"),

    Europe_2fJersey("Europe/Jersey"),

    Europe_2fKaliningrad("Europe/Kaliningrad"),

    Europe_2fKiev("Europe/Kiev"),

    Europe_2fKirov("Europe/Kirov"),

    Europe_2fLisbon("Europe/Lisbon"),

    Europe_2fLjubljana("Europe/Ljubljana"),

    Europe_2fLondon("Europe/London"),

    Europe_2fLuxembourg("Europe/Luxembourg"),

    Europe_2fMadrid("Europe/Madrid"),

    Europe_2fMalta("Europe/Malta"),

    Europe_2fMariehamn("Europe/Mariehamn"),

    Europe_2fMinsk("Europe/Minsk"),

    Europe_2fMonaco("Europe/Monaco"),

    Europe_2fMoscow("Europe/Moscow"),

    Europe_2fNicosia("Europe/Nicosia"),

    Europe_2fOslo("Europe/Oslo"),

    Europe_2fParis("Europe/Paris"),

    Europe_2fPodgorica("Europe/Podgorica"),

    Europe_2fPrague("Europe/Prague"),

    Europe_2fRiga("Europe/Riga"),

    Europe_2fRome("Europe/Rome"),

    Europe_2fSamara("Europe/Samara"),

    Europe_2fSan_Marino("Europe/San_Marino"),

    Europe_2fSarajevo("Europe/Sarajevo"),

    Europe_2fSaratov("Europe/Saratov"),

    Europe_2fSimferopol("Europe/Simferopol"),

    Europe_2fSkopje("Europe/Skopje"),

    Europe_2fSofia("Europe/Sofia"),

    Europe_2fStockholm("Europe/Stockholm"),

    Europe_2fTallinn("Europe/Tallinn"),

    Europe_2fTirane("Europe/Tirane"),

    Europe_2fTiraspol("Europe/Tiraspol"),

    Europe_2fUlyanovsk("Europe/Ulyanovsk"),

    Europe_2fUzhgorod("Europe/Uzhgorod"),

    Europe_2fVaduz("Europe/Vaduz"),

    Europe_2fVatican("Europe/Vatican"),

    Europe_2fVienna("Europe/Vienna"),

    Europe_2fVilnius("Europe/Vilnius"),

    Europe_2fVolgograd("Europe/Volgograd"),

    Europe_2fWarsaw("Europe/Warsaw"),

    Europe_2fZagreb("Europe/Zagreb"),

    Europe_2fZaporozhye("Europe/Zaporozhye"),

    Europe_2fZurich("Europe/Zurich"),

    Indian_2fAntananarivo("Indian/Antananarivo"),

    Indian_2fChagos("Indian/Chagos"),

    Indian_2fChristmas("Indian/Christmas"),

    Indian_2fCocos("Indian/Cocos"),

    Indian_2fComoro("Indian/Comoro"),

    Indian_2fKerguelen("Indian/Kerguelen"),

    Indian_2fMahe("Indian/Mahe"),

    Indian_2fMaldives("Indian/Maldives"),

    Indian_2fMauritius("Indian/Mauritius"),

    Indian_2fMayotte("Indian/Mayotte"),

    Indian_2fReunion("Indian/Reunion"),

    Mexico_2fBajaNorte("Mexico/BajaNorte"),

    Mexico_2fBajaSur("Mexico/BajaSur"),

    Mexico_2fGeneral("Mexico/General"),

    Pacific_2fApia("Pacific/Apia"),

    Pacific_2fAuckland("Pacific/Auckland"),

    Pacific_2fBougainville("Pacific/Bougainville"),

    Pacific_2fChatham("Pacific/Chatham"),

    Pacific_2fChuuk("Pacific/Chuuk"),

    Pacific_2fEaster("Pacific/Easter"),

    Pacific_2fEfate("Pacific/Efate"),

    Pacific_2fEnderbury("Pacific/Enderbury"),

    Pacific_2fFakaofo("Pacific/Fakaofo"),

    Pacific_2fFiji("Pacific/Fiji"),

    Pacific_2fFunafuti("Pacific/Funafuti"),

    Pacific_2fGalapagos("Pacific/Galapagos"),

    Pacific_2fGambier("Pacific/Gambier"),

    Pacific_2fGuadalcanal("Pacific/Guadalcanal"),

    Pacific_2fGuam("Pacific/Guam"),

    Pacific_2fHonolulu("Pacific/Honolulu"),

    Pacific_2fJohnston("Pacific/Johnston"),

    Pacific_2fKiritimati("Pacific/Kiritimati"),

    Pacific_2fKosrae("Pacific/Kosrae"),

    Pacific_2fKwajalein("Pacific/Kwajalein"),

    Pacific_2fMajuro("Pacific/Majuro"),

    Pacific_2fMarquesas("Pacific/Marquesas"),

    Pacific_2fMidway("Pacific/Midway"),

    Pacific_2fNauru("Pacific/Nauru"),

    Pacific_2fNiue("Pacific/Niue"),

    Pacific_2fNorfolk("Pacific/Norfolk"),

    Pacific_2fNoumea("Pacific/Noumea"),

    Pacific_2fPago_Pago("Pacific/Pago_Pago"),

    Pacific_2fPalau("Pacific/Palau"),

    Pacific_2fPitcairn("Pacific/Pitcairn"),

    Pacific_2fPohnpei("Pacific/Pohnpei"),

    Pacific_2fPonape("Pacific/Ponape"),

    Pacific_2fPort_Moresby("Pacific/Port_Moresby"),

    Pacific_2fRarotonga("Pacific/Rarotonga"),

    Pacific_2fSaipan("Pacific/Saipan"),

    Pacific_2fSamoa("Pacific/Samoa"),

    Pacific_2fTahiti("Pacific/Tahiti"),

    Pacific_2fTarawa("Pacific/Tarawa"),

    Pacific_2fTongatapu("Pacific/Tongatapu"),

    Pacific_2fTruk("Pacific/Truk"),

    Pacific_2fWake("Pacific/Wake"),

    Pacific_2fWallis("Pacific/Wallis"),

    Pacific_2fYap("Pacific/Yap"),

    SystemV_2fAST4("SystemV/AST4"),

    SystemV_2fAST4ADT("SystemV/AST4ADT"),

    SystemV_2fCST6("SystemV/CST6"),

    SystemV_2fCST6CDT("SystemV/CST6CDT"),

    SystemV_2fEST5("SystemV/EST5"),

    SystemV_2fEST5EDT("SystemV/EST5EDT"),

    SystemV_2fHST10("SystemV/HST10"),

    SystemV_2fMST7("SystemV/MST7"),

    SystemV_2fMST7MDT("SystemV/MST7MDT"),

    SystemV_2fPST8("SystemV/PST8"),

    SystemV_2fPST8PDT("SystemV/PST8PDT"),

    SystemV_2fYST9("SystemV/YST9"),

    SystemV_2fYST9YDT("SystemV/YST9YDT"),

    US_2fAlaska("US/Alaska"),

    US_2fAleutian("US/Aleutian"),

    US_2fArizona("US/Arizona"),

    US_2fCentral("US/Central"),

    US_2fEast_Indiana("US/East-Indiana"),

    US_2fEastern("US/Eastern"),

    US_2fHawaii("US/Hawaii"),

    US_2fIndiana_Starke("US/Indiana-Starke"),

    US_2fMichigan("US/Michigan"),

    US_2fMountain("US/Mountain"),

    US_2fPacific("US/Pacific"),

    US_2fPacific_New("US/Pacific-New"),

    US_2fSamoa("US/Samoa"),

    ACT("ACT"),

    AET("AET"),

    AGT("AGT"),

    ART("ART"),

    AST("AST"),

    BET("BET"),

    BST("BST"),

    CAT("CAT"),

    CET("CET"),

    CNT("CNT"),

    CST("CST"),

    CST6CDT("CST6CDT"),

    CTT("CTT"),

    Cuba("Cuba"),

    EAT("EAT"),

    ECT("ECT"),

    EET("EET"),

    Egypt("Egypt"),

    Eire("Eire"),

    EST("EST"),

    EST5EDT("EST5EDT"),

    GB("GB"),

    GB_Eire("GB-Eire"),

    GMT("GMT"),

    GMT0("GMT0"),

    Greenwich("Greenwich"),

    Hongkong("Hongkong"),

    HST("HST"),

    Iceland("Iceland"),

    IET("IET"),

    Iran("Iran"),

    Israel("Israel"),

    IST("IST"),

    Jamaica("Jamaica"),

    Japan("Japan"),

    JST("JST"),

    Kwajalein("Kwajalein"),

    Libya("Libya"),

    MET("MET"),

    MIT("MIT"),

    MST("MST"),

    MST7MDT("MST7MDT"),

    Navajo("Navajo"),

    NET("NET"),

    NST("NST"),

    NZ("NZ"),

    NZ_CHAT("NZ-CHAT"),

    PLT("PLT"),

    PNT("PNT"),

    Poland("Poland"),

    Portugal("Portugal"),

    PRC("PRC"),

    PRT("PRT"),

    PST("PST"),

    PST8PDT("PST8PDT"),

    ROK("ROK"),

    Singapore("Singapore"),

    SST("SST"),

    Turkey("Turkey"),

    UCT("UCT"),

    Universal("Universal"),

    UTC("UTC"),

    VST("VST"),

    W_SU("W-SU"),

    WET("WET"),

    Zulu("Zulu");

    private final String literal;

    private ProjectDatabaseServerTimezone(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "project_database_server_timezone";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
