/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.History;

import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistoryRecord extends UpdatableRecordImpl<HistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>funnyranks_stats.history.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>funnyranks_stats.history.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>funnyranks_stats.history.player_id</code>.
     */
    public void setPlayerId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>funnyranks_stats.history.player_id</code>.
     */
    @NotNull
    public UInteger getPlayerId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>funnyranks_stats.history.old_level</code>.
     */
    public void setOldLevel(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>funnyranks_stats.history.old_level</code>.
     */
    public UInteger getOldLevel() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>funnyranks_stats.history.new_level</code>.
     */
    public void setNewLevel(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>funnyranks_stats.history.new_level</code>.
     */
    public UInteger getNewLevel() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>funnyranks_stats.history.reg_datetime</code>.
     */
    public void setRegDatetime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>funnyranks_stats.history.reg_datetime</code>.
     */
    public LocalDateTime getRegDatetime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HistoryRecord
     */
    public HistoryRecord() {
        super(History.HISTORY);
    }

    /**
     * Create a detached, initialised HistoryRecord
     */
    public HistoryRecord(UInteger id, UInteger playerId, UInteger oldLevel, UInteger newLevel, LocalDateTime regDatetime) {
        super(History.HISTORY);

        setId(id);
        setPlayerId(playerId);
        setOldLevel(oldLevel);
        setNewLevel(newLevel);
        setRegDatetime(regDatetime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised HistoryRecord
     */
    public HistoryRecord(com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.pojos.History value) {
        super(History.HISTORY);

        if (value != null) {
            setId(value.getId());
            setPlayerId(value.getPlayerId());
            setOldLevel(value.getOldLevel());
            setNewLevel(value.getNewLevel());
            setRegDatetime(value.getRegDatetime());
            resetChangedOnNotNull();
        }
    }
}
