/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Rank;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RankRecord extends UpdatableRecordImpl<RankRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>funnyranks_stats.rank.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>funnyranks_stats.rank.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>funnyranks_stats.rank.level</code>.
     */
    public void setLevel(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>funnyranks_stats.rank.level</code>.
     */
    @NotNull
    public UInteger getLevel() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>funnyranks_stats.rank.kaomoji</code>.
     */
    public void setKaomoji(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>funnyranks_stats.rank.kaomoji</code>.
     */
    @NotNull
    @Size(max = 60)
    public String getKaomoji() {
        return (String) get(2);
    }

    /**
     * Setter for <code>funnyranks_stats.rank.name_ru</code>.
     */
    public void setNameRu(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>funnyranks_stats.rank.name_ru</code>.
     */
    @NotNull
    @Size(max = 60)
    public String getNameRu() {
        return (String) get(3);
    }

    /**
     * Setter for <code>funnyranks_stats.rank.name_en</code>.
     */
    public void setNameEn(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>funnyranks_stats.rank.name_en</code>.
     */
    @NotNull
    @Size(max = 60)
    public String getNameEn() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RankRecord
     */
    public RankRecord() {
        super(Rank.RANK);
    }

    /**
     * Create a detached, initialised RankRecord
     */
    public RankRecord(UInteger id, UInteger level, String kaomoji, String nameRu, String nameEn) {
        super(Rank.RANK);

        setId(id);
        setLevel(level);
        setKaomoji(kaomoji);
        setNameRu(nameRu);
        setNameEn(nameEn);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RankRecord
     */
    public RankRecord(com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.pojos.Rank value) {
        super(Rank.RANK);

        if (value != null) {
            setId(value.getId());
            setLevel(value.getLevel());
            setKaomoji(value.getKaomoji());
            setNameRu(value.getNameRu());
            setNameEn(value.getNameEn());
            resetChangedOnNotNull();
        }
    }
}
