/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * Language affects to country/city names from MaxMind GeoLite2 database
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum ProjectLanguage implements EnumType {

    en("en"),

    ru("ru");

    private final String literal;

    private ProjectLanguage(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static ProjectLanguage lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ProjectLanguage.class, literal);
    }
}
