/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetLastIp4 extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>funnyranks_stats.get_last_ip4.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.VARCHAR(15), false, false);

    /**
     * The parameter <code>funnyranks_stats.get_last_ip4.p_player_id</code>.
     */
    public static final Parameter<UInteger> P_PLAYER_ID = Internal.createParameter("p_player_id", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * Create a new routine call instance
     */
    public GetLastIp4() {
        super("get_last_ip4", FunnyranksStats.FUNNYRANKS_STATS, SQLDataType.VARCHAR(15));

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_PLAYER_ID);
    }

    /**
     * Set the <code>p_player_id</code> parameter IN value to the routine
     */
    public void setPPlayerId(UInteger value) {
        setValue(P_PLAYER_ID, value);
    }

    /**
     * Set the <code>p_player_id</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setPPlayerId(Field<UInteger> field) {
        setField(P_PLAYER_ID, field);
    }
}
