/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Historybyidorallprettyranks extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>funnyranks_stats.HistoryByIdOrAllPrettyRanks.target_id</code>.
     */
    public static final Parameter<UInteger> TARGET_ID = Internal.createParameter("target_id", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter
     * <code>funnyranks_stats.HistoryByIdOrAllPrettyRanks.display_type</code>.
     */
    public static final Parameter<String> DISPLAY_TYPE = Internal.createParameter("display_type", SQLDataType.VARCHAR(7), false, false);

    /**
     * The parameter
     * <code>funnyranks_stats.HistoryByIdOrAllPrettyRanks.lang</code>.
     */
    public static final Parameter<String> LANG = Internal.createParameter("lang", SQLDataType.VARCHAR(5), false, false);

    /**
     * The parameter
     * <code>funnyranks_stats.HistoryByIdOrAllPrettyRanks.is_unicode</code>.
     */
    public static final Parameter<Boolean> IS_UNICODE = Internal.createParameter("is_unicode", SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter
     * <code>funnyranks_stats.HistoryByIdOrAllPrettyRanks.poffset</code>.
     */
    public static final Parameter<UInteger> POFFSET = Internal.createParameter("poffset", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter
     * <code>funnyranks_stats.HistoryByIdOrAllPrettyRanks.plimit</code>.
     */
    public static final Parameter<UInteger> PLIMIT = Internal.createParameter("plimit", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * Create a new routine call instance
     */
    public Historybyidorallprettyranks() {
        super("HistoryByIdOrAllPrettyRanks", FunnyranksStats.FUNNYRANKS_STATS);

        addInParameter(TARGET_ID);
        addInParameter(DISPLAY_TYPE);
        addInParameter(LANG);
        addInParameter(IS_UNICODE);
        addInParameter(POFFSET);
        addInParameter(PLIMIT);
    }

    /**
     * Set the <code>target_id</code> parameter IN value to the routine
     */
    public void setTargetId(UInteger value) {
        setValue(TARGET_ID, value);
    }

    /**
     * Set the <code>display_type</code> parameter IN value to the routine
     */
    public void setDisplayType(String value) {
        setValue(DISPLAY_TYPE, value);
    }

    /**
     * Set the <code>lang</code> parameter IN value to the routine
     */
    public void setLang(String value) {
        setValue(LANG, value);
    }

    /**
     * Set the <code>is_unicode</code> parameter IN value to the routine
     */
    public void setIsUnicode(Boolean value) {
        setValue(IS_UNICODE, value);
    }

    /**
     * Set the <code>poffset</code> parameter IN value to the routine
     */
    public void setPoffset(UInteger value) {
        setValue(POFFSET, value);
    }

    /**
     * Set the <code>plimit</code> parameter IN value to the routine
     */
    public void setPlimit(UInteger value) {
        setValue(PLIMIT, value);
    }
}
