/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IsValidIp4 extends AbstractRoutine<Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>funnyranks_stats.is_valid_ip4.RETURN_VALUE</code>.
     */
    public static final Parameter<Boolean> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>funnyranks_stats.is_valid_ip4.ip</code>.
     */
    public static final Parameter<String> IP = Internal.createParameter("ip", SQLDataType.VARCHAR(21), false, false);

    /**
     * The parameter <code>funnyranks_stats.is_valid_ip4.nullable</code>.
     */
    public static final Parameter<Byte> NULLABLE = Internal.createParameter("nullable", SQLDataType.TINYINT, false, false);

    /**
     * The parameter <code>funnyranks_stats.is_valid_ip4.with_port</code>.
     */
    public static final Parameter<Byte> WITH_PORT = Internal.createParameter("with_port", SQLDataType.TINYINT, false, false);

    /**
     * Create a new routine call instance
     */
    public IsValidIp4() {
        super("is_valid_ip4", FunnyranksStats.FUNNYRANKS_STATS, SQLDataType.BOOLEAN);

        setReturnParameter(RETURN_VALUE);
        addInParameter(IP);
        addInParameter(NULLABLE);
        addInParameter(WITH_PORT);
    }

    /**
     * Set the <code>ip</code> parameter IN value to the routine
     */
    public void setIp(String value) {
        setValue(IP, value);
    }

    /**
     * Set the <code>ip</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setIp(Field<String> field) {
        setField(IP, field);
    }

    /**
     * Set the <code>nullable</code> parameter IN value to the routine
     */
    public void setNullable(Byte value) {
        setValue(NULLABLE, value);
    }

    /**
     * Set the <code>nullable</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setNullable(Field<Byte> field) {
        setField(NULLABLE, field);
    }

    /**
     * Set the <code>with_port</code> parameter IN value to the routine
     */
    public void setWithPort(Byte value) {
        setValue(WITH_PORT, value);
    }

    /**
     * Set the <code>with_port</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setWithPort(Field<Byte> field) {
        setField(WITH_PORT, field);
    }
}
