/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IsValidSteamid64 extends AbstractRoutine<Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>funnyranks_stats.is_valid_steamid64.RETURN_VALUE</code>.
     */
    public static final Parameter<Boolean> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>funnyranks_stats.is_valid_steamid64.steamid64</code>.
     */
    public static final Parameter<Long> STEAMID64 = Internal.createParameter("steamid64", SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>funnyranks_stats.is_valid_steamid64.nullable</code>.
     */
    public static final Parameter<Byte> NULLABLE = Internal.createParameter("nullable", SQLDataType.TINYINT, false, false);

    /**
     * Create a new routine call instance
     */
    public IsValidSteamid64() {
        super("is_valid_steamid64", FunnyranksStats.FUNNYRANKS_STATS, SQLDataType.BOOLEAN);

        setReturnParameter(RETURN_VALUE);
        addInParameter(STEAMID64);
        addInParameter(NULLABLE);
    }

    /**
     * Set the <code>steamid64</code> parameter IN value to the routine
     */
    public void setSteamid64(Long value) {
        setValue(STEAMID64, value);
    }

    /**
     * Set the <code>steamid64</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setSteamid64(Field<Long> field) {
        setField(STEAMID64, field);
    }

    /**
     * Set the <code>nullable</code> parameter IN value to the routine
     */
    public void setNullable(Byte value) {
        setValue(NULLABLE, value);
    }

    /**
     * Set the <code>nullable</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setNullable(Field<Byte> field) {
        setField(NULLABLE, field);
    }
}
