/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playerbysteamid64 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>funnyranks_stats.PlayerBySteamId64.steamId64</code>.
     */
    public static final Parameter<Long> STEAMID64 = Internal.createParameter("steamId64", SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>funnyranks_stats.PlayerBySteamId64.lang</code>.
     */
    public static final Parameter<String> LANG = Internal.createParameter("lang", SQLDataType.VARCHAR(5), false, false);

    /**
     * The parameter <code>funnyranks_stats.PlayerBySteamId64.is_unicode</code>.
     */
    public static final Parameter<Boolean> IS_UNICODE = Internal.createParameter("is_unicode", SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public Playerbysteamid64() {
        super("PlayerBySteamId64", FunnyranksStats.FUNNYRANKS_STATS);

        addInParameter(STEAMID64);
        addInParameter(LANG);
        addInParameter(IS_UNICODE);
    }

    /**
     * Set the <code>steamId64</code> parameter IN value to the routine
     */
    public void setSteamid64(Long value) {
        setValue(STEAMID64, value);
    }

    /**
     * Set the <code>lang</code> parameter IN value to the routine
     */
    public void setLang(String value) {
        setValue(LANG, value);
    }

    /**
     * Set the <code>is_unicode</code> parameter IN value to the routine
     */
    public void setIsUnicode(Boolean value) {
        setValue(IS_UNICODE, value);
    }
}
