/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playerbysteamid2 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>funnyranks_stats.PlayerBySteamId2.steamId2</code>.
     */
    public static final Parameter<String> STEAMID2 = Internal.createParameter("steamId2", SQLDataType.VARCHAR(22), false, false);

    /**
     * The parameter <code>funnyranks_stats.PlayerBySteamId2.lang</code>.
     */
    public static final Parameter<String> LANG = Internal.createParameter("lang", SQLDataType.VARCHAR(5), false, false);

    /**
     * The parameter <code>funnyranks_stats.PlayerBySteamId2.is_unicode</code>.
     */
    public static final Parameter<Boolean> IS_UNICODE = Internal.createParameter("is_unicode", SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public Playerbysteamid2() {
        super("PlayerBySteamId2", FunnyranksStats.FUNNYRANKS_STATS);

        addInParameter(STEAMID2);
        addInParameter(LANG);
        addInParameter(IS_UNICODE);
    }

    /**
     * Set the <code>steamId2</code> parameter IN value to the routine
     */
    public void setSteamid2(String value) {
        setValue(STEAMID2, value);
    }

    /**
     * Set the <code>lang</code> parameter IN value to the routine
     */
    public void setLang(String value) {
        setValue(LANG, value);
    }

    /**
     * Set the <code>is_unicode</code> parameter IN value to the routine
     */
    public void setIsUnicode(Boolean value) {
        setValue(IS_UNICODE, value);
    }
}
