/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playerbyname extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>funnyranks_stats.PlayerByName.name</code>.
     */
    public static final Parameter<String> NAME = Internal.createParameter("name", SQLDataType.VARCHAR(31), false, false);

    /**
     * The parameter <code>funnyranks_stats.PlayerByName.lang</code>.
     */
    public static final Parameter<String> LANG = Internal.createParameter("lang", SQLDataType.VARCHAR(5), false, false);

    /**
     * The parameter <code>funnyranks_stats.PlayerByName.is_unicode</code>.
     */
    public static final Parameter<Boolean> IS_UNICODE = Internal.createParameter("is_unicode", SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public Playerbyname() {
        super("PlayerByName", FunnyranksStats.FUNNYRANKS_STATS);

        addInParameter(NAME);
        addInParameter(LANG);
        addInParameter(IS_UNICODE);
    }

    /**
     * Set the <code>name</code> parameter IN value to the routine
     */
    public void setName_(String value) {
        setValue(NAME, value);
    }

    /**
     * Set the <code>lang</code> parameter IN value to the routine
     */
    public void setLang(String value) {
        setValue(LANG, value);
    }

    /**
     * Set the <code>is_unicode</code> parameter IN value to the routine
     */
    public void setIsUnicode(Boolean value) {
        setValue(IS_UNICODE, value);
    }
}
