/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Topcursor extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>funnyranks_stats.TopCursor.display_type</code>.
     */
    public static final Parameter<String> DISPLAY_TYPE = Internal.createParameter("display_type", SQLDataType.VARCHAR(7), false, false);

    /**
     * The parameter <code>funnyranks_stats.TopCursor.lang</code>.
     */
    public static final Parameter<String> LANG = Internal.createParameter("lang", SQLDataType.VARCHAR(5), false, false);

    /**
     * The parameter <code>funnyranks_stats.TopCursor.last_level</code>.
     */
    public static final Parameter<UInteger> LAST_LEVEL = Internal.createParameter("last_level", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter <code>funnyranks_stats.TopCursor.last_time_secs</code>.
     */
    public static final Parameter<UInteger> LAST_TIME_SECS = Internal.createParameter("last_time_secs", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter <code>funnyranks_stats.TopCursor.last_id</code>.
     */
    public static final Parameter<UInteger> LAST_ID = Internal.createParameter("last_id", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter <code>funnyranks_stats.TopCursor.cursor_direction</code>.
     */
    public static final Parameter<String> CURSOR_DIRECTION = Internal.createParameter("cursor_direction", SQLDataType.VARCHAR(4), false, false);

    /**
     * The parameter <code>funnyranks_stats.TopCursor.plimit</code>.
     */
    public static final Parameter<UInteger> PLIMIT = Internal.createParameter("plimit", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter <code>funnyranks_stats.TopCursor.is_unicode</code>.
     */
    public static final Parameter<Boolean> IS_UNICODE = Internal.createParameter("is_unicode", SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public Topcursor() {
        super("TopCursor", FunnyranksStats.FUNNYRANKS_STATS);

        addInParameter(DISPLAY_TYPE);
        addInParameter(LANG);
        addInParameter(LAST_LEVEL);
        addInParameter(LAST_TIME_SECS);
        addInParameter(LAST_ID);
        addInParameter(CURSOR_DIRECTION);
        addInParameter(PLIMIT);
        addInParameter(IS_UNICODE);
    }

    /**
     * Set the <code>display_type</code> parameter IN value to the routine
     */
    public void setDisplayType(String value) {
        setValue(DISPLAY_TYPE, value);
    }

    /**
     * Set the <code>lang</code> parameter IN value to the routine
     */
    public void setLang(String value) {
        setValue(LANG, value);
    }

    /**
     * Set the <code>last_level</code> parameter IN value to the routine
     */
    public void setLastLevel(UInteger value) {
        setValue(LAST_LEVEL, value);
    }

    /**
     * Set the <code>last_time_secs</code> parameter IN value to the routine
     */
    public void setLastTimeSecs(UInteger value) {
        setValue(LAST_TIME_SECS, value);
    }

    /**
     * Set the <code>last_id</code> parameter IN value to the routine
     */
    public void setLastId(UInteger value) {
        setValue(LAST_ID, value);
    }

    /**
     * Set the <code>cursor_direction</code> parameter IN value to the routine
     */
    public void setCursorDirection(String value) {
        setValue(CURSOR_DIRECTION, value);
    }

    /**
     * Set the <code>plimit</code> parameter IN value to the routine
     */
    public void setPlimit(UInteger value) {
        setValue(PLIMIT, value);
    }

    /**
     * Set the <code>is_unicode</code> parameter IN value to the routine
     */
    public void setIsUnicode(Boolean value) {
        setValue(IS_UNICODE, value);
    }
}
