/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Indexes;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerIpRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerIp extends TableImpl<PlayerIpRecord> {

    private static final long serialVersionUID = 365514032;

    /**
     * The reference instance of <code>funnyranks_stats.player_ip</code>
     */
    public static final PlayerIp PLAYER_IP = new PlayerIp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerIpRecord> getRecordType() {
        return PlayerIpRecord.class;
    }

    /**
     * The column <code>funnyranks_stats.player_ip.id</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.player_id</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.ip</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> IP = createField("ip", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.ip4</code>. Auto-generated IP format v4 - AAA.BBB.CCC.DDD
     */
    public final TableField<PlayerIpRecord, String> IP4 = createField("ip4", org.jooq.impl.SQLDataType.VARCHAR(15), this, "Auto-generated IP format v4 - AAA.BBB.CCC.DDD");

    /**
     * The column <code>funnyranks_stats.player_ip.country_name</code>.
     */
    public final TableField<PlayerIpRecord, String> COUNTRY_NAME = createField("country_name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.country_emoji</code>.
     */
    public final TableField<PlayerIpRecord, String> COUNTRY_EMOJI = createField("country_emoji", org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.reg_datetime</code>.
     */
    public final TableField<PlayerIpRecord, LocalDateTime> REG_DATETIME = createField("reg_datetime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>funnyranks_stats.player_ip</code> table reference
     */
    public PlayerIp() {
        this(DSL.name("player_ip"), null);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_ip</code> table reference
     */
    public PlayerIp(String alias) {
        this(DSL.name(alias), PLAYER_IP);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_ip</code> table reference
     */
    public PlayerIp(Name alias) {
        this(alias, PLAYER_IP);
    }

    private PlayerIp(Name alias, Table<PlayerIpRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerIp(Name alias, Table<PlayerIpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PlayerIp(Table<O> child, ForeignKey<O, PlayerIpRecord> key) {
        super(child, key, PLAYER_IP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return FunnyranksStats.FUNNYRANKS_STATS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PLAYER_IP_PLAYER_IP_IP4_IDX, Indexes.PLAYER_IP_PLAYER_IP_IP_IDX, Indexes.PLAYER_IP_PLAYER_IP_PLAYER_ID_IDX, Indexes.PLAYER_IP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PlayerIpRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PLAYER_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PlayerIpRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_IP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PlayerIpRecord>> getKeys() {
        return Arrays.<UniqueKey<PlayerIpRecord>>asList(Keys.KEY_PLAYER_IP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PlayerIpRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PlayerIpRecord, ?>>asList(Keys.PLAYER_IP_PLAYER_ID_FK);
    }

    public Player player() {
        return new Player(this, Keys.PLAYER_IP_PLAYER_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerIp as(String alias) {
        return new PlayerIp(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerIp as(Name alias) {
        return new PlayerIp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerIp rename(String name) {
        return new PlayerIp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerIp rename(Name name) {
        return new PlayerIp(name, null);
    }
}
