/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables.records;


import com.github.mbto.funnyranks.common.model.funnyranks.tables.Broker;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BrokerRecord extends UpdatableRecordImpl<BrokerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>funnyranks.broker.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>funnyranks.broker.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>funnyranks.broker.name</code>. broker name from
     * application.properties
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>funnyranks.broker.name</code>. broker name from
     * application.properties
     */
    @NotNull
    @Size(max = 45)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>funnyranks.broker.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>funnyranks.broker.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>funnyranks.broker.reg_datetime</code>.
     */
    public void setRegDatetime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>funnyranks.broker.reg_datetime</code>.
     */
    public LocalDateTime getRegDatetime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BrokerRecord
     */
    public BrokerRecord() {
        super(Broker.BROKER);
    }

    /**
     * Create a detached, initialised BrokerRecord
     */
    public BrokerRecord(UInteger id, String name, String description, LocalDateTime regDatetime) {
        super(Broker.BROKER);

        setId(id);
        setName(name);
        setDescription(description);
        setRegDatetime(regDatetime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BrokerRecord
     */
    public BrokerRecord(com.github.mbto.funnyranks.common.model.funnyranks.tables.pojos.Broker value) {
        super(Broker.BROKER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setRegDatetime(value.getRegDatetime());
            resetChangedOnNotNull();
        }
    }
}
