/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables.records;


import com.github.mbto.funnyranks.common.model.funnyranks.tables.Game;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>funnyranks.game.app_id</code>. Steam application id for
     * converting/validating UDP datagrams from
     * https://developer.valvesoftware.com/wiki/Steam_Application_IDs#Server_Files
     */
    public void setAppId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>funnyranks.game.app_id</code>. Steam application id for
     * converting/validating UDP datagrams from
     * https://developer.valvesoftware.com/wiki/Steam_Application_IDs#Server_Files
     */
    @NotNull
    public UInteger getAppId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>funnyranks.game.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>funnyranks.game.name</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>funnyranks.game.listener_port</code>. UDP port for
     * consuming game server logs
     */
    public void setListenerPort(UShort value) {
        set(2, value);
    }

    /**
     * Getter for <code>funnyranks.game.listener_port</code>. UDP port for
     * consuming game server logs
     */
    @NotNull
    public UShort getListenerPort() {
        return (UShort) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(UInteger appId, String name, UShort listenerPort) {
        super(Game.GAME);

        setAppId(appId);
        setName(name);
        setListenerPort(listenerPort);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(com.github.mbto.funnyranks.common.model.funnyranks.tables.pojos.Game value) {
        super(Game.GAME);

        if (value != null) {
            setAppId(value.getAppId());
            setName(value.getName());
            setListenerPort(value.getListenerPort());
            resetChangedOnNotNull();
        }
    }
}
