/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables.records;


import com.github.mbto.funnyranks.common.model.funnyranks.enums.ManagerRole;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Manager;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ManagerRecord extends UpdatableRecordImpl<ManagerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>funnyranks.manager.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>funnyranks.manager.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>funnyranks.manager.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>funnyranks.manager.username</code>.
     */
    @NotNull
    @Size(max = 31)
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>funnyranks.manager.password</code>.
     * https://www.browserling.com/tools/bcrypt
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>funnyranks.manager.password</code>.
     * https://www.browserling.com/tools/bcrypt
     */
    @NotNull
    @Size(max = 60)
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>funnyranks.manager.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>funnyranks.manager.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>funnyranks.manager.role</code>.
     */
    public void setRole(ManagerRole value) {
        set(4, value);
    }

    /**
     * Getter for <code>funnyranks.manager.role</code>.
     */
    public ManagerRole getRole() {
        return (ManagerRole) get(4);
    }

    /**
     * Setter for <code>funnyranks.manager.active</code>.
     */
    public void setActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>funnyranks.manager.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>funnyranks.manager.project_ids</code>.
     */
    public void setProjectIds(JSON value) {
        set(6, value);
    }

    /**
     * Getter for <code>funnyranks.manager.project_ids</code>.
     */
    public JSON getProjectIds() {
        return (JSON) get(6);
    }

    /**
     * Setter for <code>funnyranks.manager.reg_datetime</code>.
     */
    public void setRegDatetime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>funnyranks.manager.reg_datetime</code>.
     */
    public LocalDateTime getRegDatetime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManagerRecord
     */
    public ManagerRecord() {
        super(Manager.MANAGER);
    }

    /**
     * Create a detached, initialised ManagerRecord
     */
    public ManagerRecord(UInteger id, String username, String password, String description, ManagerRole role, Boolean active, JSON projectIds, LocalDateTime regDatetime) {
        super(Manager.MANAGER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setDescription(description);
        setRole(role);
        setActive(active);
        setProjectIds(projectIds);
        setRegDatetime(regDatetime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ManagerRecord
     */
    public ManagerRecord(com.github.mbto.funnyranks.common.model.funnyranks.tables.pojos.Manager value) {
        super(Manager.MANAGER);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setPassword(value.getPassword());
            setDescription(value.getDescription());
            setRole(value.getRole());
            setActive(value.getActive());
            setProjectIds(value.getProjectIds());
            setRegDatetime(value.getRegDatetime());
            resetChangedOnNotNull();
        }
    }
}
