/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables.records;


import com.github.mbto.funnyranks.common.model.funnyranks.enums.ProjectDatabaseServerTimezone;
import com.github.mbto.funnyranks.common.model.funnyranks.enums.ProjectLanguage;
import com.github.mbto.funnyranks.common.model.funnyranks.enums.ProjectMergeType;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Project;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>funnyranks.project.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>funnyranks.project.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>funnyranks.project.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>funnyranks.project.name</code>.
     */
    @NotNull
    @Size(max = 45)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>funnyranks.project.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>funnyranks.project.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>funnyranks.project.language</code>. Language affects to
     * country/city names from MaxMind GeoLite2 database
     */
    public void setLanguage(ProjectLanguage value) {
        set(3, value);
    }

    /**
     * Getter for <code>funnyranks.project.language</code>. Language affects to
     * country/city names from MaxMind GeoLite2 database
     */
    public ProjectLanguage getLanguage() {
        return (ProjectLanguage) get(3);
    }

    /**
     * Setter for <code>funnyranks.project.merge_type</code>.
     */
    public void setMergeType(ProjectMergeType value) {
        set(4, value);
    }

    /**
     * Getter for <code>funnyranks.project.merge_type</code>.
     */
    public ProjectMergeType getMergeType() {
        return (ProjectMergeType) get(4);
    }

    /**
     * Setter for <code>funnyranks.project.reg_datetime</code>.
     */
    public void setRegDatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>funnyranks.project.reg_datetime</code>.
     */
    public LocalDateTime getRegDatetime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>funnyranks.project.database_hostport</code>.
     */
    public void setDatabaseHostport(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>funnyranks.project.database_hostport</code>.
     */
    @NotNull
    @Size(max = 260)
    public String getDatabaseHostport() {
        return (String) get(6);
    }

    /**
     * Setter for <code>funnyranks.project.database_schema</code>.
     */
    public void setDatabaseSchema(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>funnyranks.project.database_schema</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getDatabaseSchema() {
        return (String) get(7);
    }

    /**
     * Setter for <code>funnyranks.project.database_username</code>.
     */
    public void setDatabaseUsername(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>funnyranks.project.database_username</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getDatabaseUsername() {
        return (String) get(8);
    }

    /**
     * Setter for <code>funnyranks.project.database_password</code>.
     */
    public void setDatabasePassword(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>funnyranks.project.database_password</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getDatabasePassword() {
        return (String) get(9);
    }

    /**
     * Setter for <code>funnyranks.project.database_server_timezone</code>.
     */
    public void setDatabaseServerTimezone(ProjectDatabaseServerTimezone value) {
        set(10, value);
    }

    /**
     * Getter for <code>funnyranks.project.database_server_timezone</code>.
     */
    @NotNull
    public ProjectDatabaseServerTimezone getDatabaseServerTimezone() {
        return (ProjectDatabaseServerTimezone) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(UInteger id, String name, String description, ProjectLanguage language, ProjectMergeType mergeType, LocalDateTime regDatetime, String databaseHostport, String databaseSchema, String databaseUsername, String databasePassword, ProjectDatabaseServerTimezone databaseServerTimezone) {
        super(Project.PROJECT);

        setId(id);
        setName(name);
        setDescription(description);
        setLanguage(language);
        setMergeType(mergeType);
        setRegDatetime(regDatetime);
        setDatabaseHostport(databaseHostport);
        setDatabaseSchema(databaseSchema);
        setDatabaseUsername(databaseUsername);
        setDatabasePassword(databasePassword);
        setDatabaseServerTimezone(databaseServerTimezone);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(com.github.mbto.funnyranks.common.model.funnyranks.tables.pojos.Project value) {
        super(Project.PROJECT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setLanguage(value.getLanguage());
            setMergeType(value.getMergeType());
            setRegDatetime(value.getRegDatetime());
            setDatabaseHostport(value.getDatabaseHostport());
            setDatabaseSchema(value.getDatabaseSchema());
            setDatabaseUsername(value.getDatabaseUsername());
            setDatabasePassword(value.getDatabasePassword());
            setDatabaseServerTimezone(value.getDatabaseServerTimezone());
            resetChangedOnNotNull();
        }
    }
}
