/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * Additional JDBC driver connection properties
 * https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DriverProperty implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private UInteger projectId;
    private String key;
    private String value;

    public DriverProperty() {}

    public DriverProperty(DriverProperty value) {
        this.id = value.id;
        this.projectId = value.projectId;
        this.key = value.key;
        this.value = value.value;
    }

    public DriverProperty(
        UInteger id,
        UInteger projectId,
        String key,
        String value
    ) {
        this.id = id;
        this.projectId = projectId;
        this.key = key;
        this.value = value;
    }

    /**
     * Getter for <code>funnyranks.driver_property.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>funnyranks.driver_property.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>funnyranks.driver_property.project_id</code>.
     */
    @NotNull
    public UInteger getProjectId() {
        return this.projectId;
    }

    /**
     * Setter for <code>funnyranks.driver_property.project_id</code>.
     */
    public void setProjectId(UInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * Getter for <code>funnyranks.driver_property.key</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>funnyranks.driver_property.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>funnyranks.driver_property.value</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>funnyranks.driver_property.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DriverProperty other = (DriverProperty) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.projectId == null) {
            if (other.projectId != null)
                return false;
        }
        else if (!this.projectId.equals(other.projectId))
            return false;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.projectId == null) ? 0 : this.projectId.hashCode());
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DriverProperty (");

        sb.append(id);
        sb.append(", ").append(projectId);
        sb.append(", ").append(key);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
