/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks;


import com.github.mbto.funnyranks.common.model.DefaultCatalog;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Broker;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.DriverProperty;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Game;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Manager;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Port;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Project;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Funnyranks extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks</code>
     */
    public static final Funnyranks FUNNYRANKS = new Funnyranks();

    /**
     * The table <code>funnyranks.broker</code>.
     */
    public final Broker BROKER = Broker.BROKER;

    /**
     * Additional JDBC driver connection properties
     * https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
     */
    public final DriverProperty DRIVER_PROPERTY = DriverProperty.DRIVER_PROPERTY;

    /**
     * The table <code>funnyranks.game</code>.
     */
    public final Game GAME = Game.GAME;

    /**
     * The table <code>funnyranks.manager</code>.
     */
    public final Manager MANAGER = Manager.MANAGER;

    /**
     * The table <code>funnyranks.port</code>.
     */
    public final Port PORT = Port.PORT;

    /**
     * The table <code>funnyranks.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * No further instances allowed
     */
    private Funnyranks() {
        super("funnyranks", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Broker.BROKER,
            DriverProperty.DRIVER_PROPERTY,
            Game.GAME,
            Manager.MANAGER,
            Port.PORT,
            Project.PROJECT
        );
    }
}
