/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks;


import com.github.mbto.funnyranks.common.model.funnyranks.tables.DriverProperty;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Port;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in funnyranks.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DRIVER_PROPERTY_DRIVER_PROPERTY_PROJECT_ID_IDX = Internal.createIndex(DSL.name("driver_property_project_id_idx"), DriverProperty.DRIVER_PROPERTY, new OrderField[] { DriverProperty.DRIVER_PROPERTY.PROJECT_ID }, false);
    public static final Index PORT_PORT_GAME_APP_ID_IDX = Internal.createIndex(DSL.name("port_game_app_id_idx"), Port.PORT, new OrderField[] { Port.PORT.GAME_APP_ID }, false);
    public static final Index PORT_PORT_PROJECT_ID_IDX = Internal.createIndex(DSL.name("port_project_id_idx"), Port.PORT, new OrderField[] { Port.PORT.PROJECT_ID }, false);
    public static final Index PORT_PORT_VALUE_IDX = Internal.createIndex(DSL.name("port_value_idx"), Port.PORT, new OrderField[] { Port.PORT.VALUE }, false);
}
