/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks;


import com.github.mbto.funnyranks.common.model.funnyranks.tables.Broker;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.DriverProperty;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Game;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Manager;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Port;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Project;


/**
 * Convenience access to all tables in funnyranks.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>funnyranks.broker</code>.
     */
    public static final Broker BROKER = Broker.BROKER;

    /**
     * Additional JDBC driver connection properties
     * https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
     */
    public static final DriverProperty DRIVER_PROPERTY = DriverProperty.DRIVER_PROPERTY;

    /**
     * The table <code>funnyranks.game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>funnyranks.manager</code>.
     */
    public static final Manager MANAGER = Manager.MANAGER;

    /**
     * The table <code>funnyranks.port</code>.
     */
    public static final Port PORT = Port.PORT;

    /**
     * The table <code>funnyranks.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;
}
