# https://github.com/mbto/funnyranks/

#logging.level.root=DEBUG
#logging.level.org.springframework.security.web=DEBUG
spring.devtools.restart.enabled=false

# jooq sql queries logging level
logging.level.org.jooq.tools.LoggerListener=DEBUG
# funnyranks logging level
logging.level.com.github.mbto.funnyranks=DEBUG

maxmind.city.mmdb.filepath=C:\\GeoLite2\\mmdb\\GeoLite2-City.mmdb
#maxmind.city.mmdb.filepath=/etc/nginx/geoip/GeoLite2-City.mmdb

# Hosting-wide funnyranks broker name
funnyranks.broker.name=broker_1

# JDBC Connection URL Syntax: https://dev.mysql.com/doc/connector-j/en/connector-j-reference-jdbc-url-format.html
# Available properties: https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
funnyranks.datasource.jdbcUrl=jdbc:mysql://127.0.0.1:3306/funnyranks
funnyranks.datasource.schema=funnyranks
funnyranks.datasource.username=funnyranks
funnyranks.datasource.password=funnyranks

# If you don't have default timezone in MySQL settings (my.ini, my.cnf, mysqld.cnf, etc...) in [mysqld] section
# Example:
# [mysqld]
# default-time-zone='+03:00' # or your time zone
#
# you can uncomment this property, and set a your timezone, to prevent an exception:
#	Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time
#	zone value 'RTZ 2 (????)' is unrecognized or represents more than one time zone. You must
#	configure either the server or JDBC driver (via the 'serverTimezone' configuration property)
# Examples:
#funnyranks.datasource.dataSourceProperties.serverTimezone=Europe/Moscow
#funnyranks.datasource.dataSourceProperties.serverTimezone=UTC

# Set other connection properties, if JDBC driver have problems with connection to MySQL:
# Example:
#funnyranks.datasource.dataSourceProperties.allowPublicKeyRetrieval=true
#funnyranks.datasource.dataSourceProperties.useSSL=false

# Maximum number of database connections in the pool.
# Pool used in frontend admin panel AND when funnyranks merging players into the funnyranks_stats.* tables.
# Depends on number of users frontend admin panel
#	AND property max_connections=151 (151 is default: https://dev.mysql.com/doc/refman/en/too-many-connections.html )
#		in MySQL settings (my.ini, my.cnf, mysqld.cnf, etc...) in [mysqld] section.
# This setting means the number of concurrent SQL transactions per second available to the funnyranks
# in regard to `funnyranks` database
funnyranks.datasource.maximumPoolSize=10

# The property controls the minimum number of idle connections that HikariCP tries to maintain in the pool,
# including both idle and in-use connections. If the idle connections dip below this value, HikariCP will make
# a best effort to restore them quickly and efficiently
funnyranks.datasource.minimumIdle=2

# Set the maximum number of milliseconds that a client will wait for a connection from the pool. If this time is exceeded
# without a connection becoming available, a SQLException will be thrown from javax.sql.DataSource.getConnection().
# Default 30sec: 30 * 1000
funnyranks.datasource.connectionTimeout=30000

# Sets the maximum number of milliseconds that the pool will wait for a connection to be validated as alive
# Default 5sec: 5 * 1000
funnyranks.datasource.validationTimeout=5000

# This property controls the maximum amount of time (in milliseconds) that a connection is allowed to sit idle in
# the pool. Whether a connection is retired as idle or not is subject to a maximum variation of +30 seconds, and
# average variation of +15 seconds. A connection will never be retired as idle before this timeout.
# A value of 0 means that idle connections are never removed from the pool.
# Default 59min: 59 * 60 * 1000
funnyranks.datasource.idleTimeout=3540000

# This property controls the maximum lifetime of a connection in the pool. When a connection reaches this timeout,
# even if recently used, it will be retired from the pool. An in-use connection will never be retired, only when
# it is idle will it be removed.
# Default 60min: 60 * 60 * 1000
funnyranks.datasource.maxLifetime=3600000

# Tuning performance and other properties: https://docs.spring.io/spring-boot/3.5.7/appendix/application-properties/index.html
# Context path of frontend admin panel, ending with /
# Example:
#	server.servlet.context-path=/somepath/ then frontend admin panel URL will be http://ip:port/somepath/
# Default is "/" will be http://ip:port/
server.servlet.context-path=/
# Server HTTP TCP port.
server.port=8080
# Maximum number of connections that the server accepts and processes at any given time. Once the limit has been reached, the operating system may still accept connections based on the "acceptCount" property.
server.tomcat.max-connections=8192
# Maximum size of the form content in any HTTP post request.
server.tomcat.max-http-form-post-size=2MB
# Maximum amount of request body to swallow.
server.tomcat.max-swallow-size=2MB
# Maximum amount of worker threads. Doesn't have an effect if virtual threads are enabled.
server.tomcat.threads.max=200
# Minimum amount of worker threads. Doesn't have an effect if virtual threads are enabled.
server.tomcat.threads.min-spare=10
# Whether to use virtual threads
spring.threads.virtual.enabled=false

spring.web.resources.static-locations=classpath:/static/

#spring.servlet.multipart.file-size-threshold=7MB
#spring.servlet.multipart.max-file-size=1MB
#spring.servlet.multipart.max-request-size=10MB
#server.error.whitelabel.enabled=false
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always

server.servlet.session.persistent=false
server.servlet.session.timeout=7d
server.servlet.session.cookie.max-age=7d
spring.session.timeout=7d

# Secret key to encrypt-decrypt value expressions exposed in rendering StreamedContents.
joinfaces.primefaces.secret=funnyranks-default-change-me-QWE

joinfaces.faces.project-stage=development
joinfaces.faces.facelets-refresh-period=0
joinfaces.faces.facelets-view-mappings=*.xhtml
joinfaces.faces.facelets-skip-comments=true
joinfaces.faces.datetimeconverter-default-timezone-is-system-timezone=true
joinfaces.faces.facelets-buffer-size=65535
joinfaces.faces.interpret-empty-string-submitted-values-as-null=true
joinfaces.mojarra.enable-restore-view11-compatibility=true
joinfaces.mojarra.force-load-configuration=true
joinfaces.primefaces.theme=glass-x
#joinfaces.primefaces.mobile.theme=glass-x
joinfaces.primefaces.submit=partial
joinfaces.primefaces.transform-metadata=true
#joinfaces.primefaces.font-awesome=true
#joinfaces.omnifaces.faces-views-scan-paths=/*.xhtml/*

joinfaces.mojarra.allowed-http-methods=*
joinfaces.primefaces.client-side-localisation=true
#joinfaces.primefaces.private-captcha-key=
#joinfaces.primefaces.public-captcha-key=
