/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.History;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerIp;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerName;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerSteamid;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Rank;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.HistoryRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerIpRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerNameRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerSteamidRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.RankRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>funnyranks_stats</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<HistoryRecord, UInteger> IDENTITY_HISTORY = Identities0.IDENTITY_HISTORY;
    public static final Identity<PlayerRecord, UInteger> IDENTITY_PLAYER = Identities0.IDENTITY_PLAYER;
    public static final Identity<PlayerIpRecord, UInteger> IDENTITY_PLAYER_IP = Identities0.IDENTITY_PLAYER_IP;
    public static final Identity<PlayerNameRecord, UInteger> IDENTITY_PLAYER_NAME = Identities0.IDENTITY_PLAYER_NAME;
    public static final Identity<PlayerSteamidRecord, UInteger> IDENTITY_PLAYER_STEAMID = Identities0.IDENTITY_PLAYER_STEAMID;
    public static final Identity<RankRecord, UInteger> IDENTITY_RANK = Identities0.IDENTITY_RANK;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HistoryRecord> KEY_HISTORY_PRIMARY = UniqueKeys0.KEY_HISTORY_PRIMARY;
    public static final UniqueKey<PlayerRecord> KEY_PLAYER_PRIMARY = UniqueKeys0.KEY_PLAYER_PRIMARY;
    public static final UniqueKey<PlayerIpRecord> KEY_PLAYER_IP_PRIMARY = UniqueKeys0.KEY_PLAYER_IP_PRIMARY;
    public static final UniqueKey<PlayerNameRecord> KEY_PLAYER_NAME_PRIMARY = UniqueKeys0.KEY_PLAYER_NAME_PRIMARY;
    public static final UniqueKey<PlayerSteamidRecord> KEY_PLAYER_STEAMID_PRIMARY = UniqueKeys0.KEY_PLAYER_STEAMID_PRIMARY;
    public static final UniqueKey<RankRecord> KEY_RANK_PRIMARY = UniqueKeys0.KEY_RANK_PRIMARY;
    public static final UniqueKey<RankRecord> KEY_RANK_RANK_LEVEL_UNIQUE = UniqueKeys0.KEY_RANK_RANK_LEVEL_UNIQUE;
    public static final UniqueKey<RankRecord> KEY_RANK_RANK_NAME_RU_UNIQUE = UniqueKeys0.KEY_RANK_RANK_NAME_RU_UNIQUE;
    public static final UniqueKey<RankRecord> KEY_RANK_RANK_NAME_EN_UNIQUE = UniqueKeys0.KEY_RANK_RANK_NAME_EN_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<HistoryRecord, PlayerRecord> HISTORY_PLAYER_ID_FK = ForeignKeys0.HISTORY_PLAYER_ID_FK;
    public static final ForeignKey<HistoryRecord, RankRecord> HISTORY_OLD_RANK_ID_FK = ForeignKeys0.HISTORY_OLD_RANK_ID_FK;
    public static final ForeignKey<HistoryRecord, RankRecord> HISTORY_NEW_RANK_ID_FK = ForeignKeys0.HISTORY_NEW_RANK_ID_FK;
    public static final ForeignKey<PlayerRecord, RankRecord> PLAYER_RANK_ID_FK = ForeignKeys0.PLAYER_RANK_ID_FK;
    public static final ForeignKey<PlayerIpRecord, PlayerRecord> PLAYER_IP_PLAYER_ID_FK = ForeignKeys0.PLAYER_IP_PLAYER_ID_FK;
    public static final ForeignKey<PlayerNameRecord, PlayerRecord> PLAYER_NAME_PLAYER_ID_FK = ForeignKeys0.PLAYER_NAME_PLAYER_ID_FK;
    public static final ForeignKey<PlayerSteamidRecord, PlayerRecord> PLAYER_STEAMID_PLAYER_ID_FK = ForeignKeys0.PLAYER_STEAMID_PLAYER_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<HistoryRecord, UInteger> IDENTITY_HISTORY = Internal.createIdentity(History.HISTORY, History.HISTORY.ID);
        public static Identity<PlayerRecord, UInteger> IDENTITY_PLAYER = Internal.createIdentity(Player.PLAYER, Player.PLAYER.ID);
        public static Identity<PlayerIpRecord, UInteger> IDENTITY_PLAYER_IP = Internal.createIdentity(PlayerIp.PLAYER_IP, PlayerIp.PLAYER_IP.ID);
        public static Identity<PlayerNameRecord, UInteger> IDENTITY_PLAYER_NAME = Internal.createIdentity(PlayerName.PLAYER_NAME, PlayerName.PLAYER_NAME.ID);
        public static Identity<PlayerSteamidRecord, UInteger> IDENTITY_PLAYER_STEAMID = Internal.createIdentity(PlayerSteamid.PLAYER_STEAMID, PlayerSteamid.PLAYER_STEAMID.ID);
        public static Identity<RankRecord, UInteger> IDENTITY_RANK = Internal.createIdentity(Rank.RANK, Rank.RANK.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<HistoryRecord> KEY_HISTORY_PRIMARY = Internal.createUniqueKey(History.HISTORY, "KEY_history_PRIMARY", History.HISTORY.ID);
        public static final UniqueKey<PlayerRecord> KEY_PLAYER_PRIMARY = Internal.createUniqueKey(Player.PLAYER, "KEY_player_PRIMARY", Player.PLAYER.ID);
        public static final UniqueKey<PlayerIpRecord> KEY_PLAYER_IP_PRIMARY = Internal.createUniqueKey(PlayerIp.PLAYER_IP, "KEY_player_ip_PRIMARY", PlayerIp.PLAYER_IP.ID);
        public static final UniqueKey<PlayerNameRecord> KEY_PLAYER_NAME_PRIMARY = Internal.createUniqueKey(PlayerName.PLAYER_NAME, "KEY_player_name_PRIMARY", PlayerName.PLAYER_NAME.ID);
        public static final UniqueKey<PlayerSteamidRecord> KEY_PLAYER_STEAMID_PRIMARY = Internal.createUniqueKey(PlayerSteamid.PLAYER_STEAMID, "KEY_player_steamid_PRIMARY", PlayerSteamid.PLAYER_STEAMID.ID);
        public static final UniqueKey<RankRecord> KEY_RANK_PRIMARY = Internal.createUniqueKey(Rank.RANK, "KEY_rank_PRIMARY", Rank.RANK.ID);
        public static final UniqueKey<RankRecord> KEY_RANK_RANK_LEVEL_UNIQUE = Internal.createUniqueKey(Rank.RANK, "KEY_rank_rank_level_UNIQUE", Rank.RANK.LEVEL);
        public static final UniqueKey<RankRecord> KEY_RANK_RANK_NAME_RU_UNIQUE = Internal.createUniqueKey(Rank.RANK, "KEY_rank_rank_name_ru_UNIQUE", Rank.RANK.NAME_RU);
        public static final UniqueKey<RankRecord> KEY_RANK_RANK_NAME_EN_UNIQUE = Internal.createUniqueKey(Rank.RANK, "KEY_rank_rank_name_en_UNIQUE", Rank.RANK.NAME_EN);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<HistoryRecord, PlayerRecord> HISTORY_PLAYER_ID_FK = Internal.createForeignKey(com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys.KEY_PLAYER_PRIMARY, History.HISTORY, "history_player_id_fk", History.HISTORY.PLAYER_ID);
        public static final ForeignKey<HistoryRecord, RankRecord> HISTORY_OLD_RANK_ID_FK = Internal.createForeignKey(com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys.KEY_RANK_PRIMARY, History.HISTORY, "history_old_rank_id_fk", History.HISTORY.OLD_RANK_ID);
        public static final ForeignKey<HistoryRecord, RankRecord> HISTORY_NEW_RANK_ID_FK = Internal.createForeignKey(com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys.KEY_RANK_PRIMARY, History.HISTORY, "history_new_rank_id_fk", History.HISTORY.NEW_RANK_ID);
        public static final ForeignKey<PlayerRecord, RankRecord> PLAYER_RANK_ID_FK = Internal.createForeignKey(com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys.KEY_RANK_PRIMARY, Player.PLAYER, "player_rank_id_fk", Player.PLAYER.RANK_ID);
        public static final ForeignKey<PlayerIpRecord, PlayerRecord> PLAYER_IP_PLAYER_ID_FK = Internal.createForeignKey(com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys.KEY_PLAYER_PRIMARY, PlayerIp.PLAYER_IP, "player_ip_player_id_fk", PlayerIp.PLAYER_IP.PLAYER_ID);
        public static final ForeignKey<PlayerNameRecord, PlayerRecord> PLAYER_NAME_PLAYER_ID_FK = Internal.createForeignKey(com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys.KEY_PLAYER_PRIMARY, PlayerName.PLAYER_NAME, "player_name_player_id_fk", PlayerName.PLAYER_NAME.PLAYER_ID);
        public static final ForeignKey<PlayerSteamidRecord, PlayerRecord> PLAYER_STEAMID_PLAYER_ID_FK = Internal.createForeignKey(com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys.KEY_PLAYER_PRIMARY, PlayerSteamid.PLAYER_STEAMID, "player_steamid_player_id_fk", PlayerSteamid.PLAYER_STEAMID.PLAYER_ID);
    }
}
