/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country implements Serializable {

    private static final long serialVersionUID = 1782844429;

    private UInteger geonameId;
    private String   emoji;
    private String   nameEn;
    private String   nameRu;

    public Country() {}

    public Country(Country value) {
        this.geonameId = value.geonameId;
        this.emoji = value.emoji;
        this.nameEn = value.nameEn;
        this.nameRu = value.nameRu;
    }

    public Country(
        UInteger geonameId,
        String   emoji,
        String   nameEn,
        String   nameRu
    ) {
        this.geonameId = geonameId;
        this.emoji = emoji;
        this.nameEn = nameEn;
        this.nameRu = nameRu;
    }

    @NotNull
    public UInteger getGeonameId() {
        return this.geonameId;
    }

    public void setGeonameId(UInteger geonameId) {
        this.geonameId = geonameId;
    }

    @Size(max = 2)
    public String getEmoji() {
        return this.emoji;
    }

    public void setEmoji(String emoji) {
        this.emoji = emoji;
    }

    @Size(max = 44)
    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    @Size(max = 41)
    public String getNameRu() {
        return this.nameRu;
    }

    public void setNameRu(String nameRu) {
        this.nameRu = nameRu;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Country other = (Country) obj;
        if (geonameId == null) {
            if (other.geonameId != null)
                return false;
        }
        else if (!geonameId.equals(other.geonameId))
            return false;
        if (emoji == null) {
            if (other.emoji != null)
                return false;
        }
        else if (!emoji.equals(other.emoji))
            return false;
        if (nameEn == null) {
            if (other.nameEn != null)
                return false;
        }
        else if (!nameEn.equals(other.nameEn))
            return false;
        if (nameRu == null) {
            if (other.nameRu != null)
                return false;
        }
        else if (!nameRu.equals(other.nameRu))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.geonameId == null) ? 0 : this.geonameId.hashCode());
        result = prime * result + ((this.emoji == null) ? 0 : this.emoji.hashCode());
        result = prime * result + ((this.nameEn == null) ? 0 : this.nameEn.hashCode());
        result = prime * result + ((this.nameRu == null) ? 0 : this.nameRu.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Country (");

        sb.append(geonameId);
        sb.append(", ").append(emoji);
        sb.append(", ").append(nameEn);
        sb.append(", ").append(nameRu);

        sb.append(")");
        return sb.toString();
    }
}
