/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ipv4 implements Serializable {

    private static final long serialVersionUID = 41115845;

    private UInteger startInt;
    private UInteger lastInt;
    private UInteger vGeonameId;

    public Ipv4() {}

    public Ipv4(Ipv4 value) {
        this.startInt = value.startInt;
        this.lastInt = value.lastInt;
        this.vGeonameId = value.vGeonameId;
    }

    public Ipv4(
        UInteger startInt,
        UInteger lastInt,
        UInteger vGeonameId
    ) {
        this.startInt = startInt;
        this.lastInt = lastInt;
        this.vGeonameId = vGeonameId;
    }

    @NotNull
    public UInteger getStartInt() {
        return this.startInt;
    }

    public void setStartInt(UInteger startInt) {
        this.startInt = startInt;
    }

    @NotNull
    public UInteger getLastInt() {
        return this.lastInt;
    }

    public void setLastInt(UInteger lastInt) {
        this.lastInt = lastInt;
    }

    @NotNull
    public UInteger getVGeonameId() {
        return this.vGeonameId;
    }

    public void setVGeonameId(UInteger vGeonameId) {
        this.vGeonameId = vGeonameId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Ipv4 other = (Ipv4) obj;
        if (startInt == null) {
            if (other.startInt != null)
                return false;
        }
        else if (!startInt.equals(other.startInt))
            return false;
        if (lastInt == null) {
            if (other.lastInt != null)
                return false;
        }
        else if (!lastInt.equals(other.lastInt))
            return false;
        if (vGeonameId == null) {
            if (other.vGeonameId != null)
                return false;
        }
        else if (!vGeonameId.equals(other.vGeonameId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.startInt == null) ? 0 : this.startInt.hashCode());
        result = prime * result + ((this.lastInt == null) ? 0 : this.lastInt.hashCode());
        result = prime * result + ((this.vGeonameId == null) ? 0 : this.vGeonameId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ipv4 (");

        sb.append(startInt);
        sb.append(", ").append(lastInt);
        sb.append(", ").append(vGeonameId);

        sb.append(")");
        return sb.toString();
    }
}
