/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Indexes;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player.PlayerPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Rank.RankPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.HistoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class History extends TableImpl<HistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks_stats.history</code>
     */
    public static final History HISTORY = new History();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HistoryRecord> getRecordType() {
        return HistoryRecord.class;
    }

    /**
     * The column <code>funnyranks_stats.history.id</code>.
     */
    public final TableField<HistoryRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks_stats.history.player_id</code>.
     */
    public final TableField<HistoryRecord, UInteger> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.history.old_level</code>.
     */
    public final TableField<HistoryRecord, UInteger> OLD_LEVEL = createField(DSL.name("old_level"), SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>funnyranks_stats.history.new_level</code>.
     */
    public final TableField<HistoryRecord, UInteger> NEW_LEVEL = createField(DSL.name("new_level"), SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>funnyranks_stats.history.reg_datetime</code>.
     */
    public final TableField<HistoryRecord, LocalDateTime> REG_DATETIME = createField(DSL.name("reg_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private History(Name alias, Table<HistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private History(Name alias, Table<HistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks_stats.history</code> table reference
     */
    public History(String alias) {
        this(DSL.name(alias), HISTORY);
    }

    /**
     * Create an aliased <code>funnyranks_stats.history</code> table reference
     */
    public History(Name alias) {
        this(alias, HISTORY);
    }

    /**
     * Create a <code>funnyranks_stats.history</code> table reference
     */
    public History() {
        this(DSL.name("history"), null);
    }

    public <O extends Record> History(Table<O> path, ForeignKey<O, HistoryRecord> childPath, InverseForeignKey<O, HistoryRecord> parentPath) {
        super(path, childPath, parentPath, HISTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HistoryPath extends History implements Path<HistoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HistoryPath(Table<O> path, ForeignKey<O, HistoryRecord> childPath, InverseForeignKey<O, HistoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HistoryPath(Name alias, Table<HistoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HistoryPath as(String alias) {
            return new HistoryPath(DSL.name(alias), this);
        }

        @Override
        public HistoryPath as(Name alias) {
            return new HistoryPath(alias, this);
        }

        @Override
        public HistoryPath as(Table<?> alias) {
            return new HistoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : FunnyranksStats.FUNNYRANKS_STATS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HISTORY_HISTORY_NEW_LEVEL_IDX, Indexes.HISTORY_HISTORY_OLD_LEVEL_IDX, Indexes.HISTORY_HISTORY_PLAYER_ID_ID_IDX);
    }

    @Override
    public Identity<HistoryRecord, UInteger> getIdentity() {
        return (Identity<HistoryRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<HistoryRecord> getPrimaryKey() {
        return Keys.KEY_HISTORY_PRIMARY;
    }

    @Override
    public List<ForeignKey<HistoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HISTORY_NEW_LEVEL_FK, Keys.HISTORY_OLD_LEVEL_FK, Keys.HISTORY_PLAYER_ID_FK);
    }

    private transient RankPath _historyNewLevelFk;

    /**
     * Get the implicit join path to the <code>funnyranks_stats.rank</code>
     * table, via the <code>history_new_level_fk</code> key.
     */
    public RankPath historyNewLevelFk() {
        if (_historyNewLevelFk == null)
            _historyNewLevelFk = new RankPath(this, Keys.HISTORY_NEW_LEVEL_FK, null);

        return _historyNewLevelFk;
    }

    private transient RankPath _historyOldLevelFk;

    /**
     * Get the implicit join path to the <code>funnyranks_stats.rank</code>
     * table, via the <code>history_old_level_fk</code> key.
     */
    public RankPath historyOldLevelFk() {
        if (_historyOldLevelFk == null)
            _historyOldLevelFk = new RankPath(this, Keys.HISTORY_OLD_LEVEL_FK, null);

        return _historyOldLevelFk;
    }

    private transient PlayerPath _player;

    /**
     * Get the implicit join path to the <code>funnyranks_stats.player</code>
     * table.
     */
    public PlayerPath player() {
        if (_player == null)
            _player = new PlayerPath(this, Keys.HISTORY_PLAYER_ID_FK, null);

        return _player;
    }

    @Override
    public History as(String alias) {
        return new History(DSL.name(alias), this);
    }

    @Override
    public History as(Name alias) {
        return new History(alias, this);
    }

    @Override
    public History as(Table<?> alias) {
        return new History(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public History rename(String name) {
        return new History(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public History rename(Name name) {
        return new History(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public History rename(Table<?> name) {
        return new History(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public History where(Condition condition) {
        return new History(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public History where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public History where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public History where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public History where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public History where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public History where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public History where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public History whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public History whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
