/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Indexes;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player.PlayerPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerIpRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerIp extends TableImpl<PlayerIpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks_stats.player_ip</code>
     */
    public static final PlayerIp PLAYER_IP = new PlayerIp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerIpRecord> getRecordType() {
        return PlayerIpRecord.class;
    }

    /**
     * The column <code>funnyranks_stats.player_ip.id</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.player_id</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.ip</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> IP = createField(DSL.name("ip"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.ip4</code>. Auto-generated IP
     * format v4 - AAA.BBB.CCC.DDD
     */
    public final TableField<PlayerIpRecord, String> IP4 = createField(DSL.name("ip4"), SQLDataType.VARCHAR(15), this, "Auto-generated IP format v4 - AAA.BBB.CCC.DDD");

    /**
     * The column <code>funnyranks_stats.player_ip.maxmind_geoname_id</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> MAXMIND_GEONAME_ID = createField(DSL.name("maxmind_geoname_id"), SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>funnyranks_stats.player_ip.reg_datetime</code>.
     */
    public final TableField<PlayerIpRecord, LocalDateTime> REG_DATETIME = createField(DSL.name("reg_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private PlayerIp(Name alias, Table<PlayerIpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlayerIp(Name alias, Table<PlayerIpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_ip</code> table reference
     */
    public PlayerIp(String alias) {
        this(DSL.name(alias), PLAYER_IP);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_ip</code> table reference
     */
    public PlayerIp(Name alias) {
        this(alias, PLAYER_IP);
    }

    /**
     * Create a <code>funnyranks_stats.player_ip</code> table reference
     */
    public PlayerIp() {
        this(DSL.name("player_ip"), null);
    }

    public <O extends Record> PlayerIp(Table<O> path, ForeignKey<O, PlayerIpRecord> childPath, InverseForeignKey<O, PlayerIpRecord> parentPath) {
        super(path, childPath, parentPath, PLAYER_IP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlayerIpPath extends PlayerIp implements Path<PlayerIpRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlayerIpPath(Table<O> path, ForeignKey<O, PlayerIpRecord> childPath, InverseForeignKey<O, PlayerIpRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlayerIpPath(Name alias, Table<PlayerIpRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlayerIpPath as(String alias) {
            return new PlayerIpPath(DSL.name(alias), this);
        }

        @Override
        public PlayerIpPath as(Name alias) {
            return new PlayerIpPath(alias, this);
        }

        @Override
        public PlayerIpPath as(Table<?> alias) {
            return new PlayerIpPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : FunnyranksStats.FUNNYRANKS_STATS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYER_IP_PLAYER_IP_FIND_IDX, Indexes.PLAYER_IP_PLAYER_IP_IP_IDX);
    }

    @Override
    public Identity<PlayerIpRecord, UInteger> getIdentity() {
        return (Identity<PlayerIpRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlayerIpRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_IP_PRIMARY;
    }

    @Override
    public List<UniqueKey<PlayerIpRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PLAYER_IP_UQX_IP);
    }

    @Override
    public List<ForeignKey<PlayerIpRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYER_IP_PLAYER_ID_FK);
    }

    private transient PlayerPath _player;

    /**
     * Get the implicit join path to the <code>funnyranks_stats.player</code>
     * table.
     */
    public PlayerPath player() {
        if (_player == null)
            _player = new PlayerPath(this, Keys.PLAYER_IP_PLAYER_ID_FK, null);

        return _player;
    }

    @Override
    public PlayerIp as(String alias) {
        return new PlayerIp(DSL.name(alias), this);
    }

    @Override
    public PlayerIp as(Name alias) {
        return new PlayerIp(alias, this);
    }

    @Override
    public PlayerIp as(Table<?> alias) {
        return new PlayerIp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerIp rename(String name) {
        return new PlayerIp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerIp rename(Name name) {
        return new PlayerIp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerIp rename(Table<?> name) {
        return new PlayerIp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerIp where(Condition condition) {
        return new PlayerIp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerIp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerIp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerIp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerIp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerIp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerIp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerIp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerIp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerIp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
