/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Indexes;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player.PlayerPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerSteamidRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerSteamid extends TableImpl<PlayerSteamidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks_stats.player_steamid</code>
     */
    public static final PlayerSteamid PLAYER_STEAMID = new PlayerSteamid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerSteamidRecord> getRecordType() {
        return PlayerSteamidRecord.class;
    }

    /**
     * The column <code>funnyranks_stats.player_steamid.id</code>.
     */
    public final TableField<PlayerSteamidRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks_stats.player_steamid.player_id</code>.
     */
    public final TableField<PlayerSteamidRecord, UInteger> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_steamid.steamid64</code>.
     */
    public final TableField<PlayerSteamidRecord, Long> STEAMID64 = createField(DSL.name("steamid64"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_steamid.steamid2</code>.
     * Auto-generated SteamID format v2 - STEAM_0:X:YYYYYYYYYY -
     * https://developer.valvesoftware.com/wiki/SteamID
     */
    public final TableField<PlayerSteamidRecord, String> STEAMID2 = createField(DSL.name("steamid2"), SQLDataType.VARCHAR(20), this, "Auto-generated SteamID format v2 - STEAM_0:X:YYYYYYYYYY - https://developer.valvesoftware.com/wiki/SteamID");

    /**
     * The column <code>funnyranks_stats.player_steamid.steamid3</code>.
     * Auto-generated SteamID format v3 - [U:X:YYYYYYYYYY] -
     * https://developer.valvesoftware.com/wiki/SteamID
     */
    public final TableField<PlayerSteamidRecord, String> STEAMID3 = createField(DSL.name("steamid3"), SQLDataType.VARCHAR(20), this, "Auto-generated SteamID format v3 - [U:X:YYYYYYYYYY] - https://developer.valvesoftware.com/wiki/SteamID");

    /**
     * The column <code>funnyranks_stats.player_steamid.reg_datetime</code>.
     */
    public final TableField<PlayerSteamidRecord, LocalDateTime> REG_DATETIME = createField(DSL.name("reg_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private PlayerSteamid(Name alias, Table<PlayerSteamidRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlayerSteamid(Name alias, Table<PlayerSteamidRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_steamid</code> table
     * reference
     */
    public PlayerSteamid(String alias) {
        this(DSL.name(alias), PLAYER_STEAMID);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_steamid</code> table
     * reference
     */
    public PlayerSteamid(Name alias) {
        this(alias, PLAYER_STEAMID);
    }

    /**
     * Create a <code>funnyranks_stats.player_steamid</code> table reference
     */
    public PlayerSteamid() {
        this(DSL.name("player_steamid"), null);
    }

    public <O extends Record> PlayerSteamid(Table<O> path, ForeignKey<O, PlayerSteamidRecord> childPath, InverseForeignKey<O, PlayerSteamidRecord> parentPath) {
        super(path, childPath, parentPath, PLAYER_STEAMID);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlayerSteamidPath extends PlayerSteamid implements Path<PlayerSteamidRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlayerSteamidPath(Table<O> path, ForeignKey<O, PlayerSteamidRecord> childPath, InverseForeignKey<O, PlayerSteamidRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlayerSteamidPath(Name alias, Table<PlayerSteamidRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlayerSteamidPath as(String alias) {
            return new PlayerSteamidPath(DSL.name(alias), this);
        }

        @Override
        public PlayerSteamidPath as(Name alias) {
            return new PlayerSteamidPath(alias, this);
        }

        @Override
        public PlayerSteamidPath as(Table<?> alias) {
            return new PlayerSteamidPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : FunnyranksStats.FUNNYRANKS_STATS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYER_STEAMID_PLAYER_STEAMID_FIND_IDX, Indexes.PLAYER_STEAMID_PLAYER_STEAMID_STEAMID64_IDX);
    }

    @Override
    public Identity<PlayerSteamidRecord, UInteger> getIdentity() {
        return (Identity<PlayerSteamidRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlayerSteamidRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_STEAMID_PRIMARY;
    }

    @Override
    public List<UniqueKey<PlayerSteamidRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PLAYER_STEAMID_UQX_STEAMID);
    }

    @Override
    public List<ForeignKey<PlayerSteamidRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYER_STEAMID_PLAYER_ID_FK);
    }

    private transient PlayerPath _player;

    /**
     * Get the implicit join path to the <code>funnyranks_stats.player</code>
     * table.
     */
    public PlayerPath player() {
        if (_player == null)
            _player = new PlayerPath(this, Keys.PLAYER_STEAMID_PLAYER_ID_FK, null);

        return _player;
    }

    @Override
    public PlayerSteamid as(String alias) {
        return new PlayerSteamid(DSL.name(alias), this);
    }

    @Override
    public PlayerSteamid as(Name alias) {
        return new PlayerSteamid(alias, this);
    }

    @Override
    public PlayerSteamid as(Table<?> alias) {
        return new PlayerSteamid(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerSteamid rename(String name) {
        return new PlayerSteamid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerSteamid rename(Name name) {
        return new PlayerSteamid(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerSteamid rename(Table<?> name) {
        return new PlayerSteamid(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerSteamid where(Condition condition) {
        return new PlayerSteamid(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerSteamid where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerSteamid where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerSteamid where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerSteamid where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerSteamid where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerSteamid where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerSteamid where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerSteamid whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerSteamid whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
