/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Indexes;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player.PlayerPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerNameRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerName extends TableImpl<PlayerNameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks_stats.player_name</code>
     */
    public static final PlayerName PLAYER_NAME = new PlayerName();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerNameRecord> getRecordType() {
        return PlayerNameRecord.class;
    }

    /**
     * The column <code>funnyranks_stats.player_name.id</code>.
     */
    public final TableField<PlayerNameRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks_stats.player_name.player_id</code>.
     */
    public final TableField<PlayerNameRecord, UInteger> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_name.name</code>.
     */
    public final TableField<PlayerNameRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(31).nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.player_name.reg_datetime</code>.
     */
    public final TableField<PlayerNameRecord, LocalDateTime> REG_DATETIME = createField(DSL.name("reg_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private PlayerName(Name alias, Table<PlayerNameRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlayerName(Name alias, Table<PlayerNameRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_name</code> table
     * reference
     */
    public PlayerName(String alias) {
        this(DSL.name(alias), PLAYER_NAME);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player_name</code> table
     * reference
     */
    public PlayerName(Name alias) {
        this(alias, PLAYER_NAME);
    }

    /**
     * Create a <code>funnyranks_stats.player_name</code> table reference
     */
    public PlayerName() {
        this(DSL.name("player_name"), null);
    }

    public <O extends Record> PlayerName(Table<O> path, ForeignKey<O, PlayerNameRecord> childPath, InverseForeignKey<O, PlayerNameRecord> parentPath) {
        super(path, childPath, parentPath, PLAYER_NAME);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlayerNamePath extends PlayerName implements Path<PlayerNameRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlayerNamePath(Table<O> path, ForeignKey<O, PlayerNameRecord> childPath, InverseForeignKey<O, PlayerNameRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlayerNamePath(Name alias, Table<PlayerNameRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlayerNamePath as(String alias) {
            return new PlayerNamePath(DSL.name(alias), this);
        }

        @Override
        public PlayerNamePath as(Name alias) {
            return new PlayerNamePath(alias, this);
        }

        @Override
        public PlayerNamePath as(Table<?> alias) {
            return new PlayerNamePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : FunnyranksStats.FUNNYRANKS_STATS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYER_NAME_PLAYER_NAME_FIND_IDX, Indexes.PLAYER_NAME_PLAYER_NAME_NAME_IDX);
    }

    @Override
    public Identity<PlayerNameRecord, UInteger> getIdentity() {
        return (Identity<PlayerNameRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlayerNameRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_NAME_PRIMARY;
    }

    @Override
    public List<UniqueKey<PlayerNameRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PLAYER_NAME_UQX_NAME);
    }

    @Override
    public List<ForeignKey<PlayerNameRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYER_NAME_PLAYER_ID_FK);
    }

    private transient PlayerPath _player;

    /**
     * Get the implicit join path to the <code>funnyranks_stats.player</code>
     * table.
     */
    public PlayerPath player() {
        if (_player == null)
            _player = new PlayerPath(this, Keys.PLAYER_NAME_PLAYER_ID_FK, null);

        return _player;
    }

    @Override
    public PlayerName as(String alias) {
        return new PlayerName(DSL.name(alias), this);
    }

    @Override
    public PlayerName as(Name alias) {
        return new PlayerName(alias, this);
    }

    @Override
    public PlayerName as(Table<?> alias) {
        return new PlayerName(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerName rename(String name) {
        return new PlayerName(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerName rename(Name name) {
        return new PlayerName(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerName rename(Table<?> name) {
        return new PlayerName(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerName where(Condition condition) {
        return new PlayerName(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerName where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerName where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerName where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerName where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerName where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerName where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlayerName where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerName whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlayerName whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
