/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Indexes;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.History.HistoryPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerIp.PlayerIpPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerName.PlayerNamePath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerSteamid.PlayerSteamidPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Rank.RankPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Player extends TableImpl<PlayerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks_stats.player</code>
     */
    public static final Player PLAYER = new Player();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerRecord> getRecordType() {
        return PlayerRecord.class;
    }

    /**
     * The column <code>funnyranks_stats.player.id</code>.
     */
    public final TableField<PlayerRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks_stats.player.kills</code>.
     */
    public final TableField<PlayerRecord, UInteger> KILLS = createField(DSL.name("kills"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>funnyranks_stats.player.deaths</code>.
     */
    public final TableField<PlayerRecord, UInteger> DEATHS = createField(DSL.name("deaths"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>funnyranks_stats.player.time_secs</code>.
     */
    public final TableField<PlayerRecord, UInteger> TIME_SECS = createField(DSL.name("time_secs"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>funnyranks_stats.player.level</code>.
     */
    public final TableField<PlayerRecord, UInteger> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>funnyranks_stats.player.stars_unicode</code>.
     */
    public final TableField<PlayerRecord, String> STARS_UNICODE = createField(DSL.name("stars_unicode"), SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>funnyranks_stats.player.stars_compat</code>.
     */
    public final TableField<PlayerRecord, String> STARS_COMPAT = createField(DSL.name("stars_compat"), SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>funnyranks_stats.player.lastseen_datetime</code>.
     */
    public final TableField<PlayerRecord, LocalDateTime> LASTSEEN_DATETIME = createField(DSL.name("lastseen_datetime"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>funnyranks_stats.player.last_server_name</code>.
     */
    public final TableField<PlayerRecord, String> LAST_SERVER_NAME = createField(DSL.name("last_server_name"), SQLDataType.VARCHAR(31), this, "");

    private Player(Name alias, Table<PlayerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Player(Name alias, Table<PlayerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player</code> table reference
     */
    public Player(String alias) {
        this(DSL.name(alias), PLAYER);
    }

    /**
     * Create an aliased <code>funnyranks_stats.player</code> table reference
     */
    public Player(Name alias) {
        this(alias, PLAYER);
    }

    /**
     * Create a <code>funnyranks_stats.player</code> table reference
     */
    public Player() {
        this(DSL.name("player"), null);
    }

    public <O extends Record> Player(Table<O> path, ForeignKey<O, PlayerRecord> childPath, InverseForeignKey<O, PlayerRecord> parentPath) {
        super(path, childPath, parentPath, PLAYER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlayerPath extends Player implements Path<PlayerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlayerPath(Table<O> path, ForeignKey<O, PlayerRecord> childPath, InverseForeignKey<O, PlayerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlayerPath(Name alias, Table<PlayerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlayerPath as(String alias) {
            return new PlayerPath(DSL.name(alias), this);
        }

        @Override
        public PlayerPath as(Name alias) {
            return new PlayerPath(alias, this);
        }

        @Override
        public PlayerPath as(Table<?> alias) {
            return new PlayerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : FunnyranksStats.FUNNYRANKS_STATS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYER_TOP_CURSOR_COVER_IDX);
    }

    @Override
    public Identity<PlayerRecord, UInteger> getIdentity() {
        return (Identity<PlayerRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlayerRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_PRIMARY;
    }

    @Override
    public List<ForeignKey<PlayerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYER_RANK_LEVEL_FK_IDX);
    }

    private transient RankPath _rank;

    /**
     * Get the implicit join path to the <code>funnyranks_stats.rank</code>
     * table.
     */
    public RankPath rank() {
        if (_rank == null)
            _rank = new RankPath(this, Keys.PLAYER_RANK_LEVEL_FK_IDX, null);

        return _rank;
    }

    private transient HistoryPath _history;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks_stats.history</code> table
     */
    public HistoryPath history() {
        if (_history == null)
            _history = new HistoryPath(this, null, Keys.HISTORY_PLAYER_ID_FK.getInverseKey());

        return _history;
    }

    private transient PlayerIpPath _playerIp;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks_stats.player_ip</code> table
     */
    public PlayerIpPath playerIp() {
        if (_playerIp == null)
            _playerIp = new PlayerIpPath(this, null, Keys.PLAYER_IP_PLAYER_ID_FK.getInverseKey());

        return _playerIp;
    }

    private transient PlayerNamePath _playerName;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks_stats.player_name</code> table
     */
    public PlayerNamePath playerName() {
        if (_playerName == null)
            _playerName = new PlayerNamePath(this, null, Keys.PLAYER_NAME_PLAYER_ID_FK.getInverseKey());

        return _playerName;
    }

    private transient PlayerSteamidPath _playerSteamid;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks_stats.player_steamid</code> table
     */
    public PlayerSteamidPath playerSteamid() {
        if (_playerSteamid == null)
            _playerSteamid = new PlayerSteamidPath(this, null, Keys.PLAYER_STEAMID_PLAYER_ID_FK.getInverseKey());

        return _playerSteamid;
    }

    @Override
    public Player as(String alias) {
        return new Player(DSL.name(alias), this);
    }

    @Override
    public Player as(Name alias) {
        return new Player(alias, this);
    }

    @Override
    public Player as(Table<?> alias) {
        return new Player(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Player rename(String name) {
        return new Player(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Player rename(Name name) {
        return new Player(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Player rename(Table<?> name) {
        return new Player(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Player where(Condition condition) {
        return new Player(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Player where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Player where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Player where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Player where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Player where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Player where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Player where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Player whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Player whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
