/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.History.HistoryPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player.PlayerPath;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.RankRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rank extends TableImpl<RankRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks_stats.rank</code>
     */
    public static final Rank RANK = new Rank();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RankRecord> getRecordType() {
        return RankRecord.class;
    }

    /**
     * The column <code>funnyranks_stats.rank.id</code>.
     */
    public final TableField<RankRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks_stats.rank.level</code>.
     */
    public final TableField<RankRecord, UInteger> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.rank.kaomoji</code>.
     */
    public final TableField<RankRecord, String> KAOMOJI = createField(DSL.name("kaomoji"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.rank.name_ru</code>.
     */
    public final TableField<RankRecord, String> NAME_RU = createField(DSL.name("name_ru"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>funnyranks_stats.rank.name_en</code>.
     */
    public final TableField<RankRecord, String> NAME_EN = createField(DSL.name("name_en"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    private Rank(Name alias, Table<RankRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Rank(Name alias, Table<RankRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks_stats.rank</code> table reference
     */
    public Rank(String alias) {
        this(DSL.name(alias), RANK);
    }

    /**
     * Create an aliased <code>funnyranks_stats.rank</code> table reference
     */
    public Rank(Name alias) {
        this(alias, RANK);
    }

    /**
     * Create a <code>funnyranks_stats.rank</code> table reference
     */
    public Rank() {
        this(DSL.name("rank"), null);
    }

    public <O extends Record> Rank(Table<O> path, ForeignKey<O, RankRecord> childPath, InverseForeignKey<O, RankRecord> parentPath) {
        super(path, childPath, parentPath, RANK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RankPath extends Rank implements Path<RankRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RankPath(Table<O> path, ForeignKey<O, RankRecord> childPath, InverseForeignKey<O, RankRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RankPath(Name alias, Table<RankRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RankPath as(String alias) {
            return new RankPath(DSL.name(alias), this);
        }

        @Override
        public RankPath as(Name alias) {
            return new RankPath(alias, this);
        }

        @Override
        public RankPath as(Table<?> alias) {
            return new RankPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : FunnyranksStats.FUNNYRANKS_STATS;
    }

    @Override
    public Identity<RankRecord, UInteger> getIdentity() {
        return (Identity<RankRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<RankRecord> getPrimaryKey() {
        return Keys.KEY_RANK_PRIMARY;
    }

    @Override
    public List<UniqueKey<RankRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_RANK_RANK_LEVEL_UNIQUE, Keys.KEY_RANK_RANK_NAME_EN_UNIQUE, Keys.KEY_RANK_RANK_NAME_RU_UNIQUE);
    }

    private transient HistoryPath _historyNewLevelFk;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks_stats.history</code> table, via the
     * <code>history_new_level_fk</code> key
     */
    public HistoryPath historyNewLevelFk() {
        if (_historyNewLevelFk == null)
            _historyNewLevelFk = new HistoryPath(this, null, Keys.HISTORY_NEW_LEVEL_FK.getInverseKey());

        return _historyNewLevelFk;
    }

    private transient HistoryPath _historyOldLevelFk;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks_stats.history</code> table, via the
     * <code>history_old_level_fk</code> key
     */
    public HistoryPath historyOldLevelFk() {
        if (_historyOldLevelFk == null)
            _historyOldLevelFk = new HistoryPath(this, null, Keys.HISTORY_OLD_LEVEL_FK.getInverseKey());

        return _historyOldLevelFk;
    }

    private transient PlayerPath _player;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks_stats.player</code> table
     */
    public PlayerPath player() {
        if (_player == null)
            _player = new PlayerPath(this, null, Keys.PLAYER_RANK_LEVEL_FK_IDX.getInverseKey());

        return _player;
    }

    @Override
    public Rank as(String alias) {
        return new Rank(DSL.name(alias), this);
    }

    @Override
    public Rank as(Name alias) {
        return new Rank(alias, this);
    }

    @Override
    public Rank as(Table<?> alias) {
        return new Rank(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rank rename(String name) {
        return new Rank(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rank rename(Name name) {
        return new Rank(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rank rename(Table<?> name) {
        return new Rank(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rank where(Condition condition) {
        return new Rank(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rank where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rank where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rank where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rank where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rank where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rank where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rank where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rank whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rank whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
