/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables;


import com.github.mbto.funnyranks.common.model.funnyranks.Funnyranks;
import com.github.mbto.funnyranks.common.model.funnyranks.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Port.PortPath;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.records.BrokerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Broker extends TableImpl<BrokerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks.broker</code>
     */
    public static final Broker BROKER = new Broker();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BrokerRecord> getRecordType() {
        return BrokerRecord.class;
    }

    /**
     * The column <code>funnyranks.broker.id</code>.
     */
    public final TableField<BrokerRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks.broker.name</code>. broker name from
     * application.properties
     */
    public final TableField<BrokerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "broker name from application.properties");

    /**
     * The column <code>funnyranks.broker.description</code>.
     */
    public final TableField<BrokerRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB(65535), this, "");

    /**
     * The column <code>funnyranks.broker.reg_datetime</code>.
     */
    public final TableField<BrokerRecord, LocalDateTime> REG_DATETIME = createField(DSL.name("reg_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Broker(Name alias, Table<BrokerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Broker(Name alias, Table<BrokerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks.broker</code> table reference
     */
    public Broker(String alias) {
        this(DSL.name(alias), BROKER);
    }

    /**
     * Create an aliased <code>funnyranks.broker</code> table reference
     */
    public Broker(Name alias) {
        this(alias, BROKER);
    }

    /**
     * Create a <code>funnyranks.broker</code> table reference
     */
    public Broker() {
        this(DSL.name("broker"), null);
    }

    public <O extends Record> Broker(Table<O> path, ForeignKey<O, BrokerRecord> childPath, InverseForeignKey<O, BrokerRecord> parentPath) {
        super(path, childPath, parentPath, BROKER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BrokerPath extends Broker implements Path<BrokerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BrokerPath(Table<O> path, ForeignKey<O, BrokerRecord> childPath, InverseForeignKey<O, BrokerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BrokerPath(Name alias, Table<BrokerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BrokerPath as(String alias) {
            return new BrokerPath(DSL.name(alias), this);
        }

        @Override
        public BrokerPath as(Name alias) {
            return new BrokerPath(alias, this);
        }

        @Override
        public BrokerPath as(Table<?> alias) {
            return new BrokerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Funnyranks.FUNNYRANKS;
    }

    @Override
    public Identity<BrokerRecord, UInteger> getIdentity() {
        return (Identity<BrokerRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<BrokerRecord> getPrimaryKey() {
        return Keys.KEY_BROKER_PRIMARY;
    }

    @Override
    public List<UniqueKey<BrokerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BROKER_BROKER_NAME_UNIQUE);
    }

    private transient PortPath _port;

    /**
     * Get the implicit to-many join path to the <code>funnyranks.port</code>
     * table
     */
    public PortPath port() {
        if (_port == null)
            _port = new PortPath(this, null, Keys.PORT_BROKER_ID_FK.getInverseKey());

        return _port;
    }

    @Override
    public Broker as(String alias) {
        return new Broker(DSL.name(alias), this);
    }

    @Override
    public Broker as(Name alias) {
        return new Broker(alias, this);
    }

    @Override
    public Broker as(Table<?> alias) {
        return new Broker(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Broker rename(String name) {
        return new Broker(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Broker rename(Name name) {
        return new Broker(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Broker rename(Table<?> name) {
        return new Broker(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Broker where(Condition condition) {
        return new Broker(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Broker where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Broker where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Broker where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Broker where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Broker where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Broker where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Broker where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Broker whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Broker whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
