/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables;


import com.github.mbto.funnyranks.common.model.funnyranks.Funnyranks;
import com.github.mbto.funnyranks.common.model.funnyranks.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Port.PortPath;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.records.GameRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Game extends TableImpl<GameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks.game</code>
     */
    public static final Game GAME = new Game();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameRecord> getRecordType() {
        return GameRecord.class;
    }

    /**
     * The column <code>funnyranks.game.app_id</code>. Steam application id for
     * converting/validating UDP datagrams from
     * https://developer.valvesoftware.com/wiki/Steam_Application_IDs#Server_Files
     */
    public final TableField<GameRecord, UInteger> APP_ID = createField(DSL.name("app_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "Steam application id for converting/validating UDP datagrams from https://developer.valvesoftware.com/wiki/Steam_Application_IDs#Server_Files");

    /**
     * The column <code>funnyranks.game.name</code>.
     */
    public final TableField<GameRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>funnyranks.game.listener_port</code>. UDP port for
     * consuming game server logs
     */
    public final TableField<GameRecord, UShort> LISTENER_PORT = createField(DSL.name("listener_port"), SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "UDP port for consuming game server logs");

    private Game(Name alias, Table<GameRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Game(Name alias, Table<GameRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks.game</code> table reference
     */
    public Game(String alias) {
        this(DSL.name(alias), GAME);
    }

    /**
     * Create an aliased <code>funnyranks.game</code> table reference
     */
    public Game(Name alias) {
        this(alias, GAME);
    }

    /**
     * Create a <code>funnyranks.game</code> table reference
     */
    public Game() {
        this(DSL.name("game"), null);
    }

    public <O extends Record> Game(Table<O> path, ForeignKey<O, GameRecord> childPath, InverseForeignKey<O, GameRecord> parentPath) {
        super(path, childPath, parentPath, GAME);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GamePath extends Game implements Path<GameRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GamePath(Table<O> path, ForeignKey<O, GameRecord> childPath, InverseForeignKey<O, GameRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GamePath(Name alias, Table<GameRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GamePath as(String alias) {
            return new GamePath(DSL.name(alias), this);
        }

        @Override
        public GamePath as(Name alias) {
            return new GamePath(alias, this);
        }

        @Override
        public GamePath as(Table<?> alias) {
            return new GamePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Funnyranks.FUNNYRANKS;
    }

    @Override
    public UniqueKey<GameRecord> getPrimaryKey() {
        return Keys.KEY_GAME_PRIMARY;
    }

    @Override
    public List<UniqueKey<GameRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_GAME_GAME_LISTENER_PORT_UNIQUE);
    }

    private transient PortPath _port;

    /**
     * Get the implicit to-many join path to the <code>funnyranks.port</code>
     * table
     */
    public PortPath port() {
        if (_port == null)
            _port = new PortPath(this, null, Keys.PORT_GAME_APP_ID_FK.getInverseKey());

        return _port;
    }

    @Override
    public Game as(String alias) {
        return new Game(DSL.name(alias), this);
    }

    @Override
    public Game as(Name alias) {
        return new Game(alias, this);
    }

    @Override
    public Game as(Table<?> alias) {
        return new Game(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(String name) {
        return new Game(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(Name name) {
        return new Game(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Game rename(Table<?> name) {
        return new Game(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Condition condition) {
        return new Game(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Game where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Game whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
