/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables;


import com.github.mbto.funnyranks.common.model.funnyranks.Funnyranks;
import com.github.mbto.funnyranks.common.model.funnyranks.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks.enums.ManagerRole;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.records.ManagerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Manager extends TableImpl<ManagerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks.manager</code>
     */
    public static final Manager MANAGER = new Manager();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManagerRecord> getRecordType() {
        return ManagerRecord.class;
    }

    /**
     * The column <code>funnyranks.manager.id</code>.
     */
    public final TableField<ManagerRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks.manager.username</code>.
     */
    public final TableField<ManagerRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(31).nullable(false), this, "");

    /**
     * The column <code>funnyranks.manager.password</code>.
     * https://www.browserling.com/tools/bcrypt
     */
    public final TableField<ManagerRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.CHAR(60).nullable(false), this, "https://www.browserling.com/tools/bcrypt");

    /**
     * The column <code>funnyranks.manager.description</code>.
     */
    public final TableField<ManagerRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB(65535), this, "");

    /**
     * The column <code>funnyranks.manager.role</code>.
     */
    public final TableField<ManagerRecord, ManagerRole> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(7).nullable(false).defaultValue(DSL.inline("project", SQLDataType.VARCHAR)).asEnumDataType(ManagerRole.class), this, "");

    /**
     * The column <code>funnyranks.manager.active</code>.
     */
    public final TableField<ManagerRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("1", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>funnyranks.manager.project_ids</code>.
     */
    public final TableField<ManagerRecord, JSON> PROJECT_IDS = createField(DSL.name("project_ids"), SQLDataType.JSON, this, "");

    /**
     * The column <code>funnyranks.manager.reg_datetime</code>.
     */
    public final TableField<ManagerRecord, LocalDateTime> REG_DATETIME = createField(DSL.name("reg_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Manager(Name alias, Table<ManagerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Manager(Name alias, Table<ManagerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks.manager</code> table reference
     */
    public Manager(String alias) {
        this(DSL.name(alias), MANAGER);
    }

    /**
     * Create an aliased <code>funnyranks.manager</code> table reference
     */
    public Manager(Name alias) {
        this(alias, MANAGER);
    }

    /**
     * Create a <code>funnyranks.manager</code> table reference
     */
    public Manager() {
        this(DSL.name("manager"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Funnyranks.FUNNYRANKS;
    }

    @Override
    public Identity<ManagerRecord, UInteger> getIdentity() {
        return (Identity<ManagerRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ManagerRecord> getPrimaryKey() {
        return Keys.KEY_MANAGER_PRIMARY;
    }

    @Override
    public List<UniqueKey<ManagerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_MANAGER_MANAGER_USERNAME_UNIQUE);
    }

    @Override
    public Manager as(String alias) {
        return new Manager(DSL.name(alias), this);
    }

    @Override
    public Manager as(Name alias) {
        return new Manager(alias, this);
    }

    @Override
    public Manager as(Table<?> alias) {
        return new Manager(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Manager rename(String name) {
        return new Manager(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Manager rename(Name name) {
        return new Manager(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Manager rename(Table<?> name) {
        return new Manager(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manager where(Condition condition) {
        return new Manager(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manager where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manager where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manager where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manager where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manager where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manager where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manager where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manager whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manager whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
