/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables;


import com.github.mbto.funnyranks.common.model.funnyranks.Funnyranks;
import com.github.mbto.funnyranks.common.model.funnyranks.Indexes;
import com.github.mbto.funnyranks.common.model.funnyranks.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Broker.BrokerPath;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Game.GamePath;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Project.ProjectPath;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.records.PortRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Port extends TableImpl<PortRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks.port</code>
     */
    public static final Port PORT = new Port();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PortRecord> getRecordType() {
        return PortRecord.class;
    }

    /**
     * The column <code>funnyranks.port.id</code>.
     */
    public final TableField<PortRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks.port.broker_id</code>.
     */
    public final TableField<PortRecord, UInteger> BROKER_ID = createField(DSL.name("broker_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks.port.project_id</code>.
     */
    public final TableField<PortRecord, UInteger> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks.port.game_app_id</code>.
     */
    public final TableField<PortRecord, UInteger> GAME_APP_ID = createField(DSL.name("game_app_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>funnyranks.port.value</code>. Local port of game server
     * from which logs will be received
     */
    public final TableField<PortRecord, UShort> VALUE = createField(DSL.name("value"), SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "Local port of game server from which logs will be received");

    /**
     * The column <code>funnyranks.port.name</code>.
     */
    public final TableField<PortRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(31).nullable(false), this, "");

    /**
     * The column <code>funnyranks.port.active</code>. Should receive packets
     * from this port?: 1-receive; 0-UDP packets from this port will be ignored
     */
    public final TableField<PortRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "Should receive packets from this port?: 1-receive; 0-UDP packets from this port will be ignored");

    /**
     * The column <code>funnyranks.port.ffa</code>. game server is FREE-FOR-ALL
     * mode (Example: CS-DeathMatch): 1-true; 0-false
     */
    public final TableField<PortRecord, Boolean> FFA = createField(DSL.name("ffa"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "game server is FREE-FOR-ALL mode (Example: CS-DeathMatch): 1-true; 0-false");

    /**
     * The column <code>funnyranks.port.ignore_bots</code>. 1-ignore statistics,
     * when killer or victim is BOT; 0-don't ignore (include all player's)
     */
    public final TableField<PortRecord, Boolean> IGNORE_BOTS = createField(DSL.name("ignore_bots"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "1-ignore statistics, when killer or victim is BOT; 0-don't ignore (include all player's)");

    /**
     * The column <code>funnyranks.port.start_session_on_action</code>. 1-start
     * player's session on event "... killed ... with ..." (not for kreedz
     * servers); 0-start player's session on event "... entered the game"
     */
    public final TableField<PortRecord, Boolean> START_SESSION_ON_ACTION = createField(DSL.name("start_session_on_action"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "1-start player's session on event \"... killed ... with ...\" (not for kreedz servers); 0-start player's session on event \"... entered the game\"");

    private Port(Name alias, Table<PortRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Port(Name alias, Table<PortRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks.port</code> table reference
     */
    public Port(String alias) {
        this(DSL.name(alias), PORT);
    }

    /**
     * Create an aliased <code>funnyranks.port</code> table reference
     */
    public Port(Name alias) {
        this(alias, PORT);
    }

    /**
     * Create a <code>funnyranks.port</code> table reference
     */
    public Port() {
        this(DSL.name("port"), null);
    }

    public <O extends Record> Port(Table<O> path, ForeignKey<O, PortRecord> childPath, InverseForeignKey<O, PortRecord> parentPath) {
        super(path, childPath, parentPath, PORT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PortPath extends Port implements Path<PortRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PortPath(Table<O> path, ForeignKey<O, PortRecord> childPath, InverseForeignKey<O, PortRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PortPath(Name alias, Table<PortRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PortPath as(String alias) {
            return new PortPath(DSL.name(alias), this);
        }

        @Override
        public PortPath as(Name alias) {
            return new PortPath(alias, this);
        }

        @Override
        public PortPath as(Table<?> alias) {
            return new PortPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Funnyranks.FUNNYRANKS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PORT_PORT_GAME_APP_ID_IDX, Indexes.PORT_PORT_PROJECT_ID_IDX, Indexes.PORT_PORT_VALUE_IDX);
    }

    @Override
    public Identity<PortRecord, UInteger> getIdentity() {
        return (Identity<PortRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<PortRecord> getPrimaryKey() {
        return Keys.KEY_PORT_PRIMARY;
    }

    @Override
    public List<UniqueKey<PortRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PORT_PORT_BROKER_ID_VALUE_UNIQ_IDX);
    }

    @Override
    public List<ForeignKey<PortRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PORT_BROKER_ID_FK, Keys.PORT_GAME_APP_ID_FK, Keys.PORT_PROJECT_ID_FK);
    }

    private transient BrokerPath _broker;

    /**
     * Get the implicit join path to the <code>funnyranks.broker</code> table.
     */
    public BrokerPath broker() {
        if (_broker == null)
            _broker = new BrokerPath(this, Keys.PORT_BROKER_ID_FK, null);

        return _broker;
    }

    private transient GamePath _game;

    /**
     * Get the implicit join path to the <code>funnyranks.game</code> table.
     */
    public GamePath game() {
        if (_game == null)
            _game = new GamePath(this, Keys.PORT_GAME_APP_ID_FK, null);

        return _game;
    }

    private transient ProjectPath _project;

    /**
     * Get the implicit join path to the <code>funnyranks.project</code> table.
     */
    public ProjectPath project() {
        if (_project == null)
            _project = new ProjectPath(this, Keys.PORT_PROJECT_ID_FK, null);

        return _project;
    }

    @Override
    public Port as(String alias) {
        return new Port(DSL.name(alias), this);
    }

    @Override
    public Port as(Name alias) {
        return new Port(alias, this);
    }

    @Override
    public Port as(Table<?> alias) {
        return new Port(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Port rename(String name) {
        return new Port(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Port rename(Name name) {
        return new Port(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Port rename(Table<?> name) {
        return new Port(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Port where(Condition condition) {
        return new Port(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Port where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Port where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Port where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Port where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Port where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Port where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Port where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Port whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Port whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
