/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks.tables;


import com.github.mbto.funnyranks.common.model.funnyranks.Funnyranks;
import com.github.mbto.funnyranks.common.model.funnyranks.Keys;
import com.github.mbto.funnyranks.common.model.funnyranks.enums.ProjectDatabaseServerTimezone;
import com.github.mbto.funnyranks.common.model.funnyranks.enums.ProjectLanguage;
import com.github.mbto.funnyranks.common.model.funnyranks.enums.ProjectMergeType;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.DriverProperty.DriverPropertyPath;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Port.PortPath;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.records.ProjectRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Project extends TableImpl<ProjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>funnyranks.project</code>
     */
    public static final Project PROJECT = new Project();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectRecord> getRecordType() {
        return ProjectRecord.class;
    }

    /**
     * The column <code>funnyranks.project.id</code>.
     */
    public final TableField<ProjectRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>funnyranks.project.name</code>.
     */
    public final TableField<ProjectRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>funnyranks.project.description</code>.
     */
    public final TableField<ProjectRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB(65535), this, "");

    /**
     * The column <code>funnyranks.project.language</code>. Language affects to
     * country/city names from MaxMind GeoLite2 database
     */
    public final TableField<ProjectRecord, ProjectLanguage> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(2).nullable(false).defaultValue(DSL.inline("en", SQLDataType.VARCHAR)).asEnumDataType(ProjectLanguage.class), this, "Language affects to country/city names from MaxMind GeoLite2 database");

    /**
     * The column <code>funnyranks.project.merge_type</code>.
     */
    public final TableField<ProjectRecord, ProjectMergeType> MERGE_TYPE = createField(DSL.name("merge_type"), SQLDataType.VARCHAR(8).nullable(false).defaultValue(DSL.inline("Nick", SQLDataType.VARCHAR)).asEnumDataType(ProjectMergeType.class), this, "");

    /**
     * The column <code>funnyranks.project.reg_datetime</code>.
     */
    public final TableField<ProjectRecord, LocalDateTime> REG_DATETIME = createField(DSL.name("reg_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>funnyranks.project.database_hostport</code>.
     */
    public final TableField<ProjectRecord, String> DATABASE_HOSTPORT = createField(DSL.name("database_hostport"), SQLDataType.VARCHAR(260).nullable(false), this, "");

    /**
     * The column <code>funnyranks.project.database_schema</code>.
     */
    public final TableField<ProjectRecord, String> DATABASE_SCHEMA = createField(DSL.name("database_schema"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>funnyranks.project.database_username</code>.
     */
    public final TableField<ProjectRecord, String> DATABASE_USERNAME = createField(DSL.name("database_username"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>funnyranks.project.database_password</code>.
     */
    public final TableField<ProjectRecord, String> DATABASE_PASSWORD = createField(DSL.name("database_password"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>funnyranks.project.database_server_timezone</code>.
     */
    public final TableField<ProjectRecord, ProjectDatabaseServerTimezone> DATABASE_SERVER_TIMEZONE = createField(DSL.name("database_server_timezone"), SQLDataType.VARCHAR(32).nullable(false).asEnumDataType(ProjectDatabaseServerTimezone.class), this, "");

    private Project(Name alias, Table<ProjectRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Project(Name alias, Table<ProjectRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>funnyranks.project</code> table reference
     */
    public Project(String alias) {
        this(DSL.name(alias), PROJECT);
    }

    /**
     * Create an aliased <code>funnyranks.project</code> table reference
     */
    public Project(Name alias) {
        this(alias, PROJECT);
    }

    /**
     * Create a <code>funnyranks.project</code> table reference
     */
    public Project() {
        this(DSL.name("project"), null);
    }

    public <O extends Record> Project(Table<O> path, ForeignKey<O, ProjectRecord> childPath, InverseForeignKey<O, ProjectRecord> parentPath) {
        super(path, childPath, parentPath, PROJECT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProjectPath extends Project implements Path<ProjectRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProjectPath(Table<O> path, ForeignKey<O, ProjectRecord> childPath, InverseForeignKey<O, ProjectRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProjectPath(Name alias, Table<ProjectRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProjectPath as(String alias) {
            return new ProjectPath(DSL.name(alias), this);
        }

        @Override
        public ProjectPath as(Name alias) {
            return new ProjectPath(alias, this);
        }

        @Override
        public ProjectPath as(Table<?> alias) {
            return new ProjectPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Funnyranks.FUNNYRANKS;
    }

    @Override
    public Identity<ProjectRecord, UInteger> getIdentity() {
        return (Identity<ProjectRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProjectRecord> getPrimaryKey() {
        return Keys.KEY_PROJECT_PRIMARY;
    }

    private transient DriverPropertyPath _driverProperty;

    /**
     * Get the implicit to-many join path to the
     * <code>funnyranks.driver_property</code> table
     */
    public DriverPropertyPath driverProperty() {
        if (_driverProperty == null)
            _driverProperty = new DriverPropertyPath(this, null, Keys.DRIVER_PROPERTY_PROJECT_ID_FK.getInverseKey());

        return _driverProperty;
    }

    private transient PortPath _port;

    /**
     * Get the implicit to-many join path to the <code>funnyranks.port</code>
     * table
     */
    public PortPath port() {
        if (_port == null)
            _port = new PortPath(this, null, Keys.PORT_PROJECT_ID_FK.getInverseKey());

        return _port;
    }

    @Override
    public Project as(String alias) {
        return new Project(DSL.name(alias), this);
    }

    @Override
    public Project as(Name alias) {
        return new Project(alias, this);
    }

    @Override
    public Project as(Table<?> alias) {
        return new Project(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Project rename(String name) {
        return new Project(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Project rename(Name name) {
        return new Project(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Project rename(Table<?> name) {
        return new Project(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Project where(Condition condition) {
        return new Project(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Project where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Project where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Project where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Project where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Project where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Project where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Project where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Project whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Project whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
