/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.routines;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.FunnyranksStats;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BuildStars extends AbstractRoutine<String> {

    private static final long serialVersionUID = 767148073;

    /**
     * The parameter <code>funnyranks_stats.build_stars.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR(6), false, false);

    /**
     * The parameter <code>funnyranks_stats.build_stars.level</code>.
     */
    public static final Parameter<UInteger> LEVEL = Internal.createParameter("level", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter <code>funnyranks_stats.build_stars.ranks_total</code>.
     */
    public static final Parameter<UInteger> RANKS_TOTAL = Internal.createParameter("ranks_total", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * Create a new routine call instance
     */
    public BuildStars() {
        super("build_stars", FunnyranksStats.FUNNYRANKS_STATS, org.jooq.impl.SQLDataType.VARCHAR(6));

        setReturnParameter(RETURN_VALUE);
        addInParameter(LEVEL);
        addInParameter(RANKS_TOTAL);
    }

    /**
     * Set the <code>level</code> parameter IN value to the routine
     */
    public void setLevel(UInteger value) {
        setValue(LEVEL, value);
    }

    /**
     * Set the <code>level</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setLevel(Field<UInteger> field) {
        setField(LEVEL, field);
    }

    /**
     * Set the <code>ranks_total</code> parameter IN value to the routine
     */
    public void setRanksTotal(UInteger value) {
        setValue(RANKS_TOTAL, value);
    }

    /**
     * Set the <code>ranks_total</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setRanksTotal(Field<UInteger> field) {
        setField(RANKS_TOTAL, field);
    }
}
