/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks;


import com.github.mbto.funnyranks.common.model.DefaultCatalog;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Broker;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.DriverProperty;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Game;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Manager;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.MaxmindDbState;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Port;
import com.github.mbto.funnyranks.common.model.funnyranks.tables.Project;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Funnyranks extends SchemaImpl {

    private static final long serialVersionUID = -100656827;

    /**
     * The reference instance of <code>funnyranks</code>
     */
    public static final Funnyranks FUNNYRANKS = new Funnyranks();

    /**
     * The table <code>funnyranks.broker</code>.
     */
    public final Broker BROKER = com.github.mbto.funnyranks.common.model.funnyranks.tables.Broker.BROKER;

    /**
     * Additional JDBC driver connection properties https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html
     */
    public final DriverProperty DRIVER_PROPERTY = com.github.mbto.funnyranks.common.model.funnyranks.tables.DriverProperty.DRIVER_PROPERTY;

    /**
     * The table <code>funnyranks.game</code>.
     */
    public final Game GAME = com.github.mbto.funnyranks.common.model.funnyranks.tables.Game.GAME;

    /**
     * The table <code>funnyranks.manager</code>.
     */
    public final Manager MANAGER = com.github.mbto.funnyranks.common.model.funnyranks.tables.Manager.MANAGER;

    /**
     * Leave or remove a link for enable/disable auto-updating GeoLite2 country database:
https://github.com/mbto/public_keeper/raw/master/funnyranks/country_en_ru.zip
     */
    public final MaxmindDbState MAXMIND_DB_STATE = com.github.mbto.funnyranks.common.model.funnyranks.tables.MaxmindDbState.MAXMIND_DB_STATE;

    /**
     * The table <code>funnyranks.port</code>.
     */
    public final Port PORT = com.github.mbto.funnyranks.common.model.funnyranks.tables.Port.PORT;

    /**
     * The table <code>funnyranks.project</code>.
     */
    public final Project PROJECT = com.github.mbto.funnyranks.common.model.funnyranks.tables.Project.PROJECT;

    /**
     * No further instances allowed
     */
    private Funnyranks() {
        super("funnyranks", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Broker.BROKER,
            DriverProperty.DRIVER_PROPERTY,
            Game.GAME,
            Manager.MANAGER,
            MaxmindDbState.MAXMIND_DB_STATE,
            Port.PORT,
            Project.PROJECT);
    }
}
