/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.History;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerIp;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerName;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerSteamid;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in funnyranks_stats.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HISTORY_HISTORY_NEW_LEVEL_IDX = Internal.createIndex(DSL.name("history_new_level_idx"), History.HISTORY, new OrderField[] { History.HISTORY.NEW_LEVEL }, false);
    public static final Index HISTORY_HISTORY_OLD_LEVEL_IDX = Internal.createIndex(DSL.name("history_old_level_idx"), History.HISTORY, new OrderField[] { History.HISTORY.OLD_LEVEL }, false);
    public static final Index HISTORY_HISTORY_PLAYER_ID_ID_IDX = Internal.createIndex(DSL.name("history_player_id_id_idx"), History.HISTORY, new OrderField[] { History.HISTORY.PLAYER_ID, History.HISTORY.ID }, false);
    public static final Index PLAYER_LASTSEEN_DATETIME_IDX = Internal.createIndex(DSL.name("lastseen_datetime_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.LASTSEEN_DATETIME }, false);
    public static final Index PLAYER_IP_PLAYER_IP_FIND_IDX = Internal.createIndex(DSL.name("player_ip_find_idx"), PlayerIp.PLAYER_IP, new OrderField[] { PlayerIp.PLAYER_IP.PLAYER_ID, PlayerIp.PLAYER_IP.REG_DATETIME, PlayerIp.PLAYER_IP.ID, PlayerIp.PLAYER_IP.IP }, false);
    public static final Index PLAYER_IP_PLAYER_IP_IP_IDX = Internal.createIndex(DSL.name("player_ip_ip_idx"), PlayerIp.PLAYER_IP, new OrderField[] { PlayerIp.PLAYER_IP.IP, PlayerIp.PLAYER_IP.REG_DATETIME, PlayerIp.PLAYER_IP.ID, PlayerIp.PLAYER_IP.PLAYER_ID }, false);
    public static final Index PLAYER_NAME_PLAYER_NAME_FIND_IDX = Internal.createIndex(DSL.name("player_name_find_idx"), PlayerName.PLAYER_NAME, new OrderField[] { PlayerName.PLAYER_NAME.PLAYER_ID, PlayerName.PLAYER_NAME.REG_DATETIME, PlayerName.PLAYER_NAME.ID, PlayerName.PLAYER_NAME.NAME }, false);
    public static final Index PLAYER_NAME_PLAYER_NAME_NAME_IDX = Internal.createIndex(DSL.name("player_name_name_idx"), PlayerName.PLAYER_NAME, new OrderField[] { PlayerName.PLAYER_NAME.NAME, PlayerName.PLAYER_NAME.REG_DATETIME, PlayerName.PLAYER_NAME.ID, PlayerName.PLAYER_NAME.PLAYER_ID }, false);
    public static final Index PLAYER_STEAMID_PLAYER_STEAMID_FIND_IDX = Internal.createIndex(DSL.name("player_steamid_find_idx"), PlayerSteamid.PLAYER_STEAMID, new OrderField[] { PlayerSteamid.PLAYER_STEAMID.PLAYER_ID, PlayerSteamid.PLAYER_STEAMID.REG_DATETIME, PlayerSteamid.PLAYER_STEAMID.ID, PlayerSteamid.PLAYER_STEAMID.STEAMID64 }, false);
    public static final Index PLAYER_STEAMID_PLAYER_STEAMID_STEAMID64_IDX = Internal.createIndex(DSL.name("player_steamid_steamid64_idx"), PlayerSteamid.PLAYER_STEAMID, new OrderField[] { PlayerSteamid.PLAYER_STEAMID.STEAMID64, PlayerSteamid.PLAYER_STEAMID.REG_DATETIME, PlayerSteamid.PLAYER_STEAMID.ID, PlayerSteamid.PLAYER_STEAMID.PLAYER_ID }, false);
    public static final Index PLAYER_TOP_CURSOR_COVER_IDX = Internal.createIndex(DSL.name("top_cursor_cover_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.LEVEL, Player.PLAYER.TIME_SECS, Player.PLAYER.ID, Player.PLAYER.KILLS, Player.PLAYER.DEATHS }, false);
}
