/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.History;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Player;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerIp;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerName;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.PlayerSteamid;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.Rank;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.HistoryRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerIpRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerNameRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.PlayerSteamidRecord;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.records.RankRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * funnyranks_stats.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HistoryRecord> KEY_HISTORY_PRIMARY = Internal.createUniqueKey(History.HISTORY, DSL.name("KEY_history_PRIMARY"), new TableField[] { History.HISTORY.ID }, true);
    public static final UniqueKey<PlayerRecord> KEY_PLAYER_PRIMARY = Internal.createUniqueKey(Player.PLAYER, DSL.name("KEY_player_PRIMARY"), new TableField[] { Player.PLAYER.ID }, true);
    public static final UniqueKey<PlayerIpRecord> KEY_PLAYER_IP_PRIMARY = Internal.createUniqueKey(PlayerIp.PLAYER_IP, DSL.name("KEY_player_ip_PRIMARY"), new TableField[] { PlayerIp.PLAYER_IP.ID }, true);
    public static final UniqueKey<PlayerIpRecord> KEY_PLAYER_IP_UQX_IP = Internal.createUniqueKey(PlayerIp.PLAYER_IP, DSL.name("KEY_player_ip_uqx_ip"), new TableField[] { PlayerIp.PLAYER_IP.PLAYER_ID, PlayerIp.PLAYER_IP.IP }, true);
    public static final UniqueKey<PlayerNameRecord> KEY_PLAYER_NAME_PRIMARY = Internal.createUniqueKey(PlayerName.PLAYER_NAME, DSL.name("KEY_player_name_PRIMARY"), new TableField[] { PlayerName.PLAYER_NAME.ID }, true);
    public static final UniqueKey<PlayerNameRecord> KEY_PLAYER_NAME_UQX_NAME = Internal.createUniqueKey(PlayerName.PLAYER_NAME, DSL.name("KEY_player_name_uqx_name"), new TableField[] { PlayerName.PLAYER_NAME.PLAYER_ID, PlayerName.PLAYER_NAME.NAME }, true);
    public static final UniqueKey<PlayerSteamidRecord> KEY_PLAYER_STEAMID_PRIMARY = Internal.createUniqueKey(PlayerSteamid.PLAYER_STEAMID, DSL.name("KEY_player_steamid_PRIMARY"), new TableField[] { PlayerSteamid.PLAYER_STEAMID.ID }, true);
    public static final UniqueKey<PlayerSteamidRecord> KEY_PLAYER_STEAMID_UQX_STEAMID = Internal.createUniqueKey(PlayerSteamid.PLAYER_STEAMID, DSL.name("KEY_player_steamid_uqx_steamid"), new TableField[] { PlayerSteamid.PLAYER_STEAMID.PLAYER_ID, PlayerSteamid.PLAYER_STEAMID.STEAMID64 }, true);
    public static final UniqueKey<RankRecord> KEY_RANK_PRIMARY = Internal.createUniqueKey(Rank.RANK, DSL.name("KEY_rank_PRIMARY"), new TableField[] { Rank.RANK.ID }, true);
    public static final UniqueKey<RankRecord> KEY_RANK_RANK_LEVEL_UNIQUE = Internal.createUniqueKey(Rank.RANK, DSL.name("KEY_rank_rank_level_UNIQUE"), new TableField[] { Rank.RANK.LEVEL }, true);
    public static final UniqueKey<RankRecord> KEY_RANK_RANK_NAME_EN_UNIQUE = Internal.createUniqueKey(Rank.RANK, DSL.name("KEY_rank_rank_name_en_UNIQUE"), new TableField[] { Rank.RANK.NAME_EN }, true);
    public static final UniqueKey<RankRecord> KEY_RANK_RANK_NAME_RU_UNIQUE = Internal.createUniqueKey(Rank.RANK, DSL.name("KEY_rank_rank_name_ru_UNIQUE"), new TableField[] { Rank.RANK.NAME_RU }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<HistoryRecord, RankRecord> HISTORY_NEW_LEVEL_FK = Internal.createForeignKey(History.HISTORY, DSL.name("history_new_level_fk"), new TableField[] { History.HISTORY.NEW_LEVEL }, Keys.KEY_RANK_RANK_LEVEL_UNIQUE, new TableField[] { Rank.RANK.LEVEL }, true);
    public static final ForeignKey<HistoryRecord, RankRecord> HISTORY_OLD_LEVEL_FK = Internal.createForeignKey(History.HISTORY, DSL.name("history_old_level_fk"), new TableField[] { History.HISTORY.OLD_LEVEL }, Keys.KEY_RANK_RANK_LEVEL_UNIQUE, new TableField[] { Rank.RANK.LEVEL }, true);
    public static final ForeignKey<HistoryRecord, PlayerRecord> HISTORY_PLAYER_ID_FK = Internal.createForeignKey(History.HISTORY, DSL.name("history_player_id_fk"), new TableField[] { History.HISTORY.PLAYER_ID }, Keys.KEY_PLAYER_PRIMARY, new TableField[] { Player.PLAYER.ID }, true);
    public static final ForeignKey<PlayerRecord, RankRecord> PLAYER_RANK_LEVEL_FK_IDX = Internal.createForeignKey(Player.PLAYER, DSL.name("player_rank_level_fk_idx"), new TableField[] { Player.PLAYER.LEVEL }, Keys.KEY_RANK_RANK_LEVEL_UNIQUE, new TableField[] { Rank.RANK.LEVEL }, true);
    public static final ForeignKey<PlayerIpRecord, PlayerRecord> PLAYER_IP_PLAYER_ID_FK = Internal.createForeignKey(PlayerIp.PLAYER_IP, DSL.name("player_ip_player_id_fk"), new TableField[] { PlayerIp.PLAYER_IP.PLAYER_ID }, Keys.KEY_PLAYER_PRIMARY, new TableField[] { Player.PLAYER.ID }, true);
    public static final ForeignKey<PlayerNameRecord, PlayerRecord> PLAYER_NAME_PLAYER_ID_FK = Internal.createForeignKey(PlayerName.PLAYER_NAME, DSL.name("player_name_player_id_fk"), new TableField[] { PlayerName.PLAYER_NAME.PLAYER_ID }, Keys.KEY_PLAYER_PRIMARY, new TableField[] { Player.PLAYER.ID }, true);
    public static final ForeignKey<PlayerSteamidRecord, PlayerRecord> PLAYER_STEAMID_PLAYER_ID_FK = Internal.createForeignKey(PlayerSteamid.PLAYER_STEAMID, DSL.name("player_steamid_player_id_fk"), new TableField[] { PlayerSteamid.PLAYER_STEAMID.PLAYER_ID }, Keys.KEY_PLAYER_PRIMARY, new TableField[] { Player.PLAYER.ID }, true);
}
