/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats;


import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.BuildHumanTime;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.BuildStarsCompat;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.BuildStarsUnicode;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.CalculateLevel;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.ConvertSteamid2ToSteamid64;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.ConvertSteamid64ToSteamid2;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Declension;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.GetLastIp4;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.GetLastName;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.GetLastSteamid2;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Historybyidorall;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Historybyidorallprettyranks;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.IsValidIp4;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.IsValidSteamid2;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.IsValidSteamid64;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Playerbyid;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Playerbyip;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Playerbyname;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Playerbysteamid2;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Playerbysteamid64;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Top;
import com.github.mbto.funnyranks.common.model.funnyranks_stats.routines.Topcursor;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.types.UInteger;


/**
 * Convenience access to all stored procedures and functions in
 * funnyranks_stats.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>funnyranks_stats.build_human_time</code>
     */
    public static String buildHumanTime(
          Configuration configuration
        , UInteger timeSecs
        , String lang
    ) {
        BuildHumanTime f = new BuildHumanTime();
        f.setTimeSecs(timeSecs);
        f.setLang(lang);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.build_human_time</code> as a field.
     */
    public static Field<String> buildHumanTime(
          UInteger timeSecs
        , String lang
    ) {
        BuildHumanTime f = new BuildHumanTime();
        f.setTimeSecs(timeSecs);
        f.setLang(lang);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.build_human_time</code> as a field.
     */
    public static Field<String> buildHumanTime(
          Field<UInteger> timeSecs
        , Field<String> lang
    ) {
        BuildHumanTime f = new BuildHumanTime();
        f.setTimeSecs(timeSecs);
        f.setLang(lang);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.build_stars_compat</code>
     */
    public static String buildStarsCompat(
          Configuration configuration
        , UInteger level
        , UInteger ranksTotal
    ) {
        BuildStarsCompat f = new BuildStarsCompat();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.build_stars_compat</code> as a field.
     */
    public static Field<String> buildStarsCompat(
          UInteger level
        , UInteger ranksTotal
    ) {
        BuildStarsCompat f = new BuildStarsCompat();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.build_stars_compat</code> as a field.
     */
    public static Field<String> buildStarsCompat(
          Field<UInteger> level
        , Field<UInteger> ranksTotal
    ) {
        BuildStarsCompat f = new BuildStarsCompat();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.build_stars_unicode</code>
     */
    public static String buildStarsUnicode(
          Configuration configuration
        , UInteger level
        , UInteger ranksTotal
    ) {
        BuildStarsUnicode f = new BuildStarsUnicode();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.build_stars_unicode</code> as a field.
     */
    public static Field<String> buildStarsUnicode(
          UInteger level
        , UInteger ranksTotal
    ) {
        BuildStarsUnicode f = new BuildStarsUnicode();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.build_stars_unicode</code> as a field.
     */
    public static Field<String> buildStarsUnicode(
          Field<UInteger> level
        , Field<UInteger> ranksTotal
    ) {
        BuildStarsUnicode f = new BuildStarsUnicode();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.calculate_level</code>
     */
    public static UInteger calculateLevel(
          Configuration configuration
        , UInteger kills
        , UInteger deaths
        , UInteger timeSecs
        , UInteger ranksCount
    ) {
        CalculateLevel f = new CalculateLevel();
        f.setKills(kills);
        f.setDeaths(deaths);
        f.setTimeSecs(timeSecs);
        f.setRanksCount(ranksCount);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.calculate_level</code> as a field.
     */
    public static Field<UInteger> calculateLevel(
          UInteger kills
        , UInteger deaths
        , UInteger timeSecs
        , UInteger ranksCount
    ) {
        CalculateLevel f = new CalculateLevel();
        f.setKills(kills);
        f.setDeaths(deaths);
        f.setTimeSecs(timeSecs);
        f.setRanksCount(ranksCount);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.calculate_level</code> as a field.
     */
    public static Field<UInteger> calculateLevel(
          Field<UInteger> kills
        , Field<UInteger> deaths
        , Field<UInteger> timeSecs
        , Field<UInteger> ranksCount
    ) {
        CalculateLevel f = new CalculateLevel();
        f.setKills(kills);
        f.setDeaths(deaths);
        f.setTimeSecs(timeSecs);
        f.setRanksCount(ranksCount);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.convert_steamid2_to_steamid64</code>
     */
    public static Long convertSteamid2ToSteamid64(
          Configuration configuration
        , String steamid2
    ) {
        ConvertSteamid2ToSteamid64 f = new ConvertSteamid2ToSteamid64();
        f.setSteamid2(steamid2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.convert_steamid2_to_steamid64</code> as a
     * field.
     */
    public static Field<Long> convertSteamid2ToSteamid64(
          String steamid2
    ) {
        ConvertSteamid2ToSteamid64 f = new ConvertSteamid2ToSteamid64();
        f.setSteamid2(steamid2);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.convert_steamid2_to_steamid64</code> as a
     * field.
     */
    public static Field<Long> convertSteamid2ToSteamid64(
          Field<String> steamid2
    ) {
        ConvertSteamid2ToSteamid64 f = new ConvertSteamid2ToSteamid64();
        f.setSteamid2(steamid2);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.convert_steamid64_to_steamid2</code>
     */
    public static String convertSteamid64ToSteamid2(
          Configuration configuration
        , Long steamid64
    ) {
        ConvertSteamid64ToSteamid2 f = new ConvertSteamid64ToSteamid2();
        f.setSteamid64(steamid64);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.convert_steamid64_to_steamid2</code> as a
     * field.
     */
    public static Field<String> convertSteamid64ToSteamid2(
          Long steamid64
    ) {
        ConvertSteamid64ToSteamid2 f = new ConvertSteamid64ToSteamid2();
        f.setSteamid64(steamid64);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.convert_steamid64_to_steamid2</code> as a
     * field.
     */
    public static Field<String> convertSteamid64ToSteamid2(
          Field<Long> steamid64
    ) {
        ConvertSteamid64ToSteamid2 f = new ConvertSteamid64ToSteamid2();
        f.setSteamid64(steamid64);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.declension</code>
     */
    public static String declension(
          Configuration configuration
        , Integer value
        , String opt1
        , String opt2
        , String opt3
    ) {
        Declension f = new Declension();
        f.setValue(value);
        f.setOpt1(opt1);
        f.setOpt2(opt2);
        f.setOpt3(opt3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.declension</code> as a field.
     */
    public static Field<String> declension(
          Integer value
        , String opt1
        , String opt2
        , String opt3
    ) {
        Declension f = new Declension();
        f.setValue(value);
        f.setOpt1(opt1);
        f.setOpt2(opt2);
        f.setOpt3(opt3);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.declension</code> as a field.
     */
    public static Field<String> declension(
          Field<Integer> value
        , Field<String> opt1
        , Field<String> opt2
        , Field<String> opt3
    ) {
        Declension f = new Declension();
        f.setValue(value);
        f.setOpt1(opt1);
        f.setOpt2(opt2);
        f.setOpt3(opt3);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.get_last_ip4</code>
     */
    public static String getLastIp4(
          Configuration configuration
        , UInteger pPlayerId
    ) {
        GetLastIp4 f = new GetLastIp4();
        f.setPPlayerId(pPlayerId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.get_last_ip4</code> as a field.
     */
    public static Field<String> getLastIp4(
          UInteger pPlayerId
    ) {
        GetLastIp4 f = new GetLastIp4();
        f.setPPlayerId(pPlayerId);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.get_last_ip4</code> as a field.
     */
    public static Field<String> getLastIp4(
          Field<UInteger> pPlayerId
    ) {
        GetLastIp4 f = new GetLastIp4();
        f.setPPlayerId(pPlayerId);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.get_last_name</code>
     */
    public static String getLastName(
          Configuration configuration
        , UInteger pPlayerId
    ) {
        GetLastName f = new GetLastName();
        f.setPPlayerId(pPlayerId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.get_last_name</code> as a field.
     */
    public static Field<String> getLastName(
          UInteger pPlayerId
    ) {
        GetLastName f = new GetLastName();
        f.setPPlayerId(pPlayerId);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.get_last_name</code> as a field.
     */
    public static Field<String> getLastName(
          Field<UInteger> pPlayerId
    ) {
        GetLastName f = new GetLastName();
        f.setPPlayerId(pPlayerId);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.get_last_steamid2</code>
     */
    public static String getLastSteamid2(
          Configuration configuration
        , UInteger pPlayerId
    ) {
        GetLastSteamid2 f = new GetLastSteamid2();
        f.setPPlayerId(pPlayerId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.get_last_steamid2</code> as a field.
     */
    public static Field<String> getLastSteamid2(
          UInteger pPlayerId
    ) {
        GetLastSteamid2 f = new GetLastSteamid2();
        f.setPPlayerId(pPlayerId);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.get_last_steamid2</code> as a field.
     */
    public static Field<String> getLastSteamid2(
          Field<UInteger> pPlayerId
    ) {
        GetLastSteamid2 f = new GetLastSteamid2();
        f.setPPlayerId(pPlayerId);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.HistoryByIdOrAll</code>
     */
    public static void historybyidorall(
          Configuration configuration
        , UInteger targetId
        , String displayType
        , String lang
        , Boolean isUnicode
        , UInteger poffset
        , UInteger plimit
    ) {
        Historybyidorall p = new Historybyidorall();
        p.setTargetId(targetId);
        p.setDisplayType(displayType);
        p.setLang(lang);
        p.setIsUnicode(isUnicode);
        p.setPoffset(poffset);
        p.setPlimit(plimit);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.HistoryByIdOrAllPrettyRanks</code>
     */
    public static void historybyidorallprettyranks(
          Configuration configuration
        , UInteger targetId
        , String displayType
        , String lang
        , Boolean isUnicode
        , UInteger poffset
        , UInteger plimit
    ) {
        Historybyidorallprettyranks p = new Historybyidorallprettyranks();
        p.setTargetId(targetId);
        p.setDisplayType(displayType);
        p.setLang(lang);
        p.setIsUnicode(isUnicode);
        p.setPoffset(poffset);
        p.setPlimit(plimit);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.is_valid_ip4</code>
     */
    public static Boolean isValidIp4(
          Configuration configuration
        , String ip
        , Byte nullable
        , Byte withPort
    ) {
        IsValidIp4 f = new IsValidIp4();
        f.setIp(ip);
        f.setNullable(nullable);
        f.setWithPort(withPort);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.is_valid_ip4</code> as a field.
     */
    public static Field<Boolean> isValidIp4(
          String ip
        , Byte nullable
        , Byte withPort
    ) {
        IsValidIp4 f = new IsValidIp4();
        f.setIp(ip);
        f.setNullable(nullable);
        f.setWithPort(withPort);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.is_valid_ip4</code> as a field.
     */
    public static Field<Boolean> isValidIp4(
          Field<String> ip
        , Field<Byte> nullable
        , Field<Byte> withPort
    ) {
        IsValidIp4 f = new IsValidIp4();
        f.setIp(ip);
        f.setNullable(nullable);
        f.setWithPort(withPort);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.is_valid_steamid2</code>
     */
    public static Boolean isValidSteamid2(
          Configuration configuration
        , String steamid2
        , Byte nullable
        , Byte onlyLegal
    ) {
        IsValidSteamid2 f = new IsValidSteamid2();
        f.setSteamid2(steamid2);
        f.setNullable(nullable);
        f.setOnlyLegal(onlyLegal);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.is_valid_steamid2</code> as a field.
     */
    public static Field<Boolean> isValidSteamid2(
          String steamid2
        , Byte nullable
        , Byte onlyLegal
    ) {
        IsValidSteamid2 f = new IsValidSteamid2();
        f.setSteamid2(steamid2);
        f.setNullable(nullable);
        f.setOnlyLegal(onlyLegal);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.is_valid_steamid2</code> as a field.
     */
    public static Field<Boolean> isValidSteamid2(
          Field<String> steamid2
        , Field<Byte> nullable
        , Field<Byte> onlyLegal
    ) {
        IsValidSteamid2 f = new IsValidSteamid2();
        f.setSteamid2(steamid2);
        f.setNullable(nullable);
        f.setOnlyLegal(onlyLegal);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.is_valid_steamid64</code>
     */
    public static Boolean isValidSteamid64(
          Configuration configuration
        , Long steamid64
        , Byte nullable
    ) {
        IsValidSteamid64 f = new IsValidSteamid64();
        f.setSteamid64(steamid64);
        f.setNullable(nullable);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>funnyranks_stats.is_valid_steamid64</code> as a field.
     */
    public static Field<Boolean> isValidSteamid64(
          Long steamid64
        , Byte nullable
    ) {
        IsValidSteamid64 f = new IsValidSteamid64();
        f.setSteamid64(steamid64);
        f.setNullable(nullable);

        return f.asField();
    }

    /**
     * Get <code>funnyranks_stats.is_valid_steamid64</code> as a field.
     */
    public static Field<Boolean> isValidSteamid64(
          Field<Long> steamid64
        , Field<Byte> nullable
    ) {
        IsValidSteamid64 f = new IsValidSteamid64();
        f.setSteamid64(steamid64);
        f.setNullable(nullable);

        return f.asField();
    }

    /**
     * Call <code>funnyranks_stats.PlayerById</code>
     */
    public static void playerbyid(
          Configuration configuration
        , String displayType
        , UInteger targetId
        , String lang
        , Boolean isUnicode
    ) {
        Playerbyid p = new Playerbyid();
        p.setDisplayType(displayType);
        p.setTargetId(targetId);
        p.setLang(lang);
        p.setIsUnicode(isUnicode);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.PlayerByIp</code>
     */
    public static void playerbyip(
          Configuration configuration
        , String ip
        , String lang
        , Boolean isUnicode
    ) {
        Playerbyip p = new Playerbyip();
        p.setIp(ip);
        p.setLang(lang);
        p.setIsUnicode(isUnicode);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.PlayerByName</code>
     */
    public static void playerbyname(
          Configuration configuration
        , String name
        , String lang
        , Boolean isUnicode
    ) {
        Playerbyname p = new Playerbyname();
        p.setName_(name);
        p.setLang(lang);
        p.setIsUnicode(isUnicode);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.PlayerBySteamId2</code>
     */
    public static void playerbysteamid2(
          Configuration configuration
        , String steamid2
        , String lang
        , Boolean isUnicode
    ) {
        Playerbysteamid2 p = new Playerbysteamid2();
        p.setSteamid2(steamid2);
        p.setLang(lang);
        p.setIsUnicode(isUnicode);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.PlayerBySteamId64</code>
     */
    public static void playerbysteamid64(
          Configuration configuration
        , Long steamid64
        , String lang
        , Boolean isUnicode
    ) {
        Playerbysteamid64 p = new Playerbysteamid64();
        p.setSteamid64(steamid64);
        p.setLang(lang);
        p.setIsUnicode(isUnicode);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.Top</code>
     */
    public static void top(
          Configuration configuration
        , String displayType
        , String lang
        , UInteger poffset
        , UInteger plimit
        , Boolean isUnicode
    ) {
        Top p = new Top();
        p.setDisplayType(displayType);
        p.setLang(lang);
        p.setPoffset(poffset);
        p.setPlimit(plimit);
        p.setIsUnicode(isUnicode);

        p.execute(configuration);
    }

    /**
     * Call <code>funnyranks_stats.TopCursor</code>
     */
    public static void topcursor(
          Configuration configuration
        , String displayType
        , String lang
        , UInteger lastLevel
        , UInteger lastTimeSecs
        , UInteger lastId
        , String cursorDirection
        , UInteger plimit
        , Boolean isUnicode
    ) {
        Topcursor p = new Topcursor();
        p.setDisplayType(displayType);
        p.setLang(lang);
        p.setLastLevel(lastLevel);
        p.setLastTimeSecs(lastTimeSecs);
        p.setLastId(lastId);
        p.setCursorDirection(cursorDirection);
        p.setPlimit(plimit);
        p.setIsUnicode(isUnicode);

        p.execute(configuration);
    }
}
