/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerSteamid implements Serializable {

    private static final long serialVersionUID = -1738713891;

    private UInteger      id;
    private UInteger      playerId;
    private Long          steamid64;
    private String        steamid2;
    private String        steamid3;
    private LocalDateTime regDatetime;

    public PlayerSteamid() {}

    public PlayerSteamid(PlayerSteamid value) {
        this.id = value.id;
        this.playerId = value.playerId;
        this.steamid64 = value.steamid64;
        this.steamid2 = value.steamid2;
        this.steamid3 = value.steamid3;
        this.regDatetime = value.regDatetime;
    }

    public PlayerSteamid(
        UInteger      id,
        UInteger      playerId,
        Long          steamid64,
        String        steamid2,
        String        steamid3,
        LocalDateTime regDatetime
    ) {
        this.id = id;
        this.playerId = playerId;
        this.steamid64 = steamid64;
        this.steamid2 = steamid2;
        this.steamid3 = steamid3;
        this.regDatetime = regDatetime;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    public UInteger getPlayerId() {
        return this.playerId;
    }

    public void setPlayerId(UInteger playerId) {
        this.playerId = playerId;
    }

    @NotNull
    public Long getSteamid64() {
        return this.steamid64;
    }

    public void setSteamid64(Long steamid64) {
        this.steamid64 = steamid64;
    }

    @Size(max = 20)
    public String getSteamid2() {
        return this.steamid2;
    }

    public void setSteamid2(String steamid2) {
        this.steamid2 = steamid2;
    }

    @Size(max = 20)
    public String getSteamid3() {
        return this.steamid3;
    }

    public void setSteamid3(String steamid3) {
        this.steamid3 = steamid3;
    }

    public LocalDateTime getRegDatetime() {
        return this.regDatetime;
    }

    public void setRegDatetime(LocalDateTime regDatetime) {
        this.regDatetime = regDatetime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlayerSteamid other = (PlayerSteamid) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (playerId == null) {
            if (other.playerId != null)
                return false;
        }
        else if (!playerId.equals(other.playerId))
            return false;
        if (steamid64 == null) {
            if (other.steamid64 != null)
                return false;
        }
        else if (!steamid64.equals(other.steamid64))
            return false;
        if (steamid2 == null) {
            if (other.steamid2 != null)
                return false;
        }
        else if (!steamid2.equals(other.steamid2))
            return false;
        if (steamid3 == null) {
            if (other.steamid3 != null)
                return false;
        }
        else if (!steamid3.equals(other.steamid3))
            return false;
        if (regDatetime == null) {
            if (other.regDatetime != null)
                return false;
        }
        else if (!regDatetime.equals(other.regDatetime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.playerId == null) ? 0 : this.playerId.hashCode());
        result = prime * result + ((this.steamid64 == null) ? 0 : this.steamid64.hashCode());
        result = prime * result + ((this.steamid2 == null) ? 0 : this.steamid2.hashCode());
        result = prime * result + ((this.steamid3 == null) ? 0 : this.steamid3.hashCode());
        result = prime * result + ((this.regDatetime == null) ? 0 : this.regDatetime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerSteamid (");

        sb.append(id);
        sb.append(", ").append(playerId);
        sb.append(", ").append(steamid64);
        sb.append(", ").append(steamid2);
        sb.append(", ").append(steamid3);
        sb.append(", ").append(regDatetime);

        sb.append(")");
        return sb.toString();
    }
}
