/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rank implements Serializable {

    private static final long serialVersionUID = -1662074966;

    private UInteger id;
    private UInteger level;
    private String   kaomoji;
    private String   nameRu;
    private String   nameEn;

    public Rank() {}

    public Rank(Rank value) {
        this.id = value.id;
        this.level = value.level;
        this.kaomoji = value.kaomoji;
        this.nameRu = value.nameRu;
        this.nameEn = value.nameEn;
    }

    public Rank(
        UInteger id,
        UInteger level,
        String   kaomoji,
        String   nameRu,
        String   nameEn
    ) {
        this.id = id;
        this.level = level;
        this.kaomoji = kaomoji;
        this.nameRu = nameRu;
        this.nameEn = nameEn;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    public UInteger getLevel() {
        return this.level;
    }

    public void setLevel(UInteger level) {
        this.level = level;
    }

    @NotNull
    @Size(max = 60)
    public String getKaomoji() {
        return this.kaomoji;
    }

    public void setKaomoji(String kaomoji) {
        this.kaomoji = kaomoji;
    }

    @NotNull
    @Size(max = 60)
    public String getNameRu() {
        return this.nameRu;
    }

    public void setNameRu(String nameRu) {
        this.nameRu = nameRu;
    }

    @NotNull
    @Size(max = 60)
    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Rank other = (Rank) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (level == null) {
            if (other.level != null)
                return false;
        }
        else if (!level.equals(other.level))
            return false;
        if (kaomoji == null) {
            if (other.kaomoji != null)
                return false;
        }
        else if (!kaomoji.equals(other.kaomoji))
            return false;
        if (nameRu == null) {
            if (other.nameRu != null)
                return false;
        }
        else if (!nameRu.equals(other.nameRu))
            return false;
        if (nameEn == null) {
            if (other.nameEn != null)
                return false;
        }
        else if (!nameEn.equals(other.nameEn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        result = prime * result + ((this.kaomoji == null) ? 0 : this.kaomoji.hashCode());
        result = prime * result + ((this.nameRu == null) ? 0 : this.nameRu.hashCode());
        result = prime * result + ((this.nameEn == null) ? 0 : this.nameEn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rank (");

        sb.append(id);
        sb.append(", ").append(level);
        sb.append(", ").append(kaomoji);
        sb.append(", ").append(nameRu);
        sb.append(", ").append(nameEn);

        sb.append(")");
        return sb.toString();
    }
}
