/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.pojos;


import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class History implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private UInteger playerId;
    private UInteger oldLevel;
    private UInteger newLevel;
    private LocalDateTime regDatetime;

    public History() {}

    public History(History value) {
        this.id = value.id;
        this.playerId = value.playerId;
        this.oldLevel = value.oldLevel;
        this.newLevel = value.newLevel;
        this.regDatetime = value.regDatetime;
    }

    public History(
        UInteger id,
        UInteger playerId,
        UInteger oldLevel,
        UInteger newLevel,
        LocalDateTime regDatetime
    ) {
        this.id = id;
        this.playerId = playerId;
        this.oldLevel = oldLevel;
        this.newLevel = newLevel;
        this.regDatetime = regDatetime;
    }

    /**
     * Getter for <code>funnyranks_stats.history.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>funnyranks_stats.history.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>funnyranks_stats.history.player_id</code>.
     */
    @NotNull
    public UInteger getPlayerId() {
        return this.playerId;
    }

    /**
     * Setter for <code>funnyranks_stats.history.player_id</code>.
     */
    public void setPlayerId(UInteger playerId) {
        this.playerId = playerId;
    }

    /**
     * Getter for <code>funnyranks_stats.history.old_level</code>.
     */
    public UInteger getOldLevel() {
        return this.oldLevel;
    }

    /**
     * Setter for <code>funnyranks_stats.history.old_level</code>.
     */
    public void setOldLevel(UInteger oldLevel) {
        this.oldLevel = oldLevel;
    }

    /**
     * Getter for <code>funnyranks_stats.history.new_level</code>.
     */
    public UInteger getNewLevel() {
        return this.newLevel;
    }

    /**
     * Setter for <code>funnyranks_stats.history.new_level</code>.
     */
    public void setNewLevel(UInteger newLevel) {
        this.newLevel = newLevel;
    }

    /**
     * Getter for <code>funnyranks_stats.history.reg_datetime</code>.
     */
    public LocalDateTime getRegDatetime() {
        return this.regDatetime;
    }

    /**
     * Setter for <code>funnyranks_stats.history.reg_datetime</code>.
     */
    public void setRegDatetime(LocalDateTime regDatetime) {
        this.regDatetime = regDatetime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final History other = (History) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.playerId == null) {
            if (other.playerId != null)
                return false;
        }
        else if (!this.playerId.equals(other.playerId))
            return false;
        if (this.oldLevel == null) {
            if (other.oldLevel != null)
                return false;
        }
        else if (!this.oldLevel.equals(other.oldLevel))
            return false;
        if (this.newLevel == null) {
            if (other.newLevel != null)
                return false;
        }
        else if (!this.newLevel.equals(other.newLevel))
            return false;
        if (this.regDatetime == null) {
            if (other.regDatetime != null)
                return false;
        }
        else if (!this.regDatetime.equals(other.regDatetime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.playerId == null) ? 0 : this.playerId.hashCode());
        result = prime * result + ((this.oldLevel == null) ? 0 : this.oldLevel.hashCode());
        result = prime * result + ((this.newLevel == null) ? 0 : this.newLevel.hashCode());
        result = prime * result + ((this.regDatetime == null) ? 0 : this.regDatetime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("History (");

        sb.append(id);
        sb.append(", ").append(playerId);
        sb.append(", ").append(oldLevel);
        sb.append(", ").append(newLevel);
        sb.append(", ").append(regDatetime);

        sb.append(")");
        return sb.toString();
    }
}
