/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerIp implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private UInteger playerId;
    private UInteger ip;
    private String ip4;
    private UInteger maxmindGeonameId;
    private LocalDateTime regDatetime;

    public PlayerIp() {}

    public PlayerIp(PlayerIp value) {
        this.id = value.id;
        this.playerId = value.playerId;
        this.ip = value.ip;
        this.ip4 = value.ip4;
        this.maxmindGeonameId = value.maxmindGeonameId;
        this.regDatetime = value.regDatetime;
    }

    public PlayerIp(
        UInteger id,
        UInteger playerId,
        UInteger ip,
        String ip4,
        UInteger maxmindGeonameId,
        LocalDateTime regDatetime
    ) {
        this.id = id;
        this.playerId = playerId;
        this.ip = ip;
        this.ip4 = ip4;
        this.maxmindGeonameId = maxmindGeonameId;
        this.regDatetime = regDatetime;
    }

    /**
     * Getter for <code>funnyranks_stats.player_ip.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>funnyranks_stats.player_ip.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>funnyranks_stats.player_ip.player_id</code>.
     */
    @NotNull
    public UInteger getPlayerId() {
        return this.playerId;
    }

    /**
     * Setter for <code>funnyranks_stats.player_ip.player_id</code>.
     */
    public void setPlayerId(UInteger playerId) {
        this.playerId = playerId;
    }

    /**
     * Getter for <code>funnyranks_stats.player_ip.ip</code>.
     */
    @NotNull
    public UInteger getIp() {
        return this.ip;
    }

    /**
     * Setter for <code>funnyranks_stats.player_ip.ip</code>.
     */
    public void setIp(UInteger ip) {
        this.ip = ip;
    }

    /**
     * Getter for <code>funnyranks_stats.player_ip.ip4</code>. Auto-generated IP
     * format v4 - AAA.BBB.CCC.DDD
     */
    @Size(max = 15)
    public String getIp4() {
        return this.ip4;
    }

    /**
     * Setter for <code>funnyranks_stats.player_ip.ip4</code>. Auto-generated IP
     * format v4 - AAA.BBB.CCC.DDD
     */
    public void setIp4(String ip4) {
        this.ip4 = ip4;
    }

    /**
     * Getter for <code>funnyranks_stats.player_ip.maxmind_geoname_id</code>.
     */
    public UInteger getMaxmindGeonameId() {
        return this.maxmindGeonameId;
    }

    /**
     * Setter for <code>funnyranks_stats.player_ip.maxmind_geoname_id</code>.
     */
    public void setMaxmindGeonameId(UInteger maxmindGeonameId) {
        this.maxmindGeonameId = maxmindGeonameId;
    }

    /**
     * Getter for <code>funnyranks_stats.player_ip.reg_datetime</code>.
     */
    public LocalDateTime getRegDatetime() {
        return this.regDatetime;
    }

    /**
     * Setter for <code>funnyranks_stats.player_ip.reg_datetime</code>.
     */
    public void setRegDatetime(LocalDateTime regDatetime) {
        this.regDatetime = regDatetime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlayerIp other = (PlayerIp) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.playerId == null) {
            if (other.playerId != null)
                return false;
        }
        else if (!this.playerId.equals(other.playerId))
            return false;
        if (this.ip == null) {
            if (other.ip != null)
                return false;
        }
        else if (!this.ip.equals(other.ip))
            return false;
        if (this.ip4 == null) {
            if (other.ip4 != null)
                return false;
        }
        else if (!this.ip4.equals(other.ip4))
            return false;
        if (this.maxmindGeonameId == null) {
            if (other.maxmindGeonameId != null)
                return false;
        }
        else if (!this.maxmindGeonameId.equals(other.maxmindGeonameId))
            return false;
        if (this.regDatetime == null) {
            if (other.regDatetime != null)
                return false;
        }
        else if (!this.regDatetime.equals(other.regDatetime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.playerId == null) ? 0 : this.playerId.hashCode());
        result = prime * result + ((this.ip == null) ? 0 : this.ip.hashCode());
        result = prime * result + ((this.ip4 == null) ? 0 : this.ip4.hashCode());
        result = prime * result + ((this.maxmindGeonameId == null) ? 0 : this.maxmindGeonameId.hashCode());
        result = prime * result + ((this.regDatetime == null) ? 0 : this.regDatetime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerIp (");

        sb.append(id);
        sb.append(", ").append(playerId);
        sb.append(", ").append(ip);
        sb.append(", ").append(ip4);
        sb.append(", ").append(maxmindGeonameId);
        sb.append(", ").append(regDatetime);

        sb.append(")");
        return sb.toString();
    }
}
