/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_stats.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rank implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private UInteger level;
    private String kaomoji;
    private String nameRu;
    private String nameEn;

    public Rank() {}

    public Rank(Rank value) {
        this.id = value.id;
        this.level = value.level;
        this.kaomoji = value.kaomoji;
        this.nameRu = value.nameRu;
        this.nameEn = value.nameEn;
    }

    public Rank(
        UInteger id,
        UInteger level,
        String kaomoji,
        String nameRu,
        String nameEn
    ) {
        this.id = id;
        this.level = level;
        this.kaomoji = kaomoji;
        this.nameRu = nameRu;
        this.nameEn = nameEn;
    }

    /**
     * Getter for <code>funnyranks_stats.rank.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>funnyranks_stats.rank.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>funnyranks_stats.rank.level</code>.
     */
    @NotNull
    public UInteger getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>funnyranks_stats.rank.level</code>.
     */
    public void setLevel(UInteger level) {
        this.level = level;
    }

    /**
     * Getter for <code>funnyranks_stats.rank.kaomoji</code>.
     */
    @NotNull
    @Size(max = 60)
    public String getKaomoji() {
        return this.kaomoji;
    }

    /**
     * Setter for <code>funnyranks_stats.rank.kaomoji</code>.
     */
    public void setKaomoji(String kaomoji) {
        this.kaomoji = kaomoji;
    }

    /**
     * Getter for <code>funnyranks_stats.rank.name_ru</code>.
     */
    @NotNull
    @Size(max = 60)
    public String getNameRu() {
        return this.nameRu;
    }

    /**
     * Setter for <code>funnyranks_stats.rank.name_ru</code>.
     */
    public void setNameRu(String nameRu) {
        this.nameRu = nameRu;
    }

    /**
     * Getter for <code>funnyranks_stats.rank.name_en</code>.
     */
    @NotNull
    @Size(max = 60)
    public String getNameEn() {
        return this.nameEn;
    }

    /**
     * Setter for <code>funnyranks_stats.rank.name_en</code>.
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Rank other = (Rank) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.level == null) {
            if (other.level != null)
                return false;
        }
        else if (!this.level.equals(other.level))
            return false;
        if (this.kaomoji == null) {
            if (other.kaomoji != null)
                return false;
        }
        else if (!this.kaomoji.equals(other.kaomoji))
            return false;
        if (this.nameRu == null) {
            if (other.nameRu != null)
                return false;
        }
        else if (!this.nameRu.equals(other.nameRu))
            return false;
        if (this.nameEn == null) {
            if (other.nameEn != null)
                return false;
        }
        else if (!this.nameEn.equals(other.nameEn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        result = prime * result + ((this.kaomoji == null) ? 0 : this.kaomoji.hashCode());
        result = prime * result + ((this.nameRu == null) ? 0 : this.nameRu.hashCode());
        result = prime * result + ((this.nameEn == null) ? 0 : this.nameEn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rank (");

        sb.append(id);
        sb.append(", ").append(level);
        sb.append(", ").append(kaomoji);
        sb.append(", ").append(nameRu);
        sb.append(", ").append(nameEn);

        sb.append(")");
        return sb.toString();
    }
}
