/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country;


import com.github.mbto.funnyranks.common.model.DefaultCatalog;
import com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Country;
import com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Ipv4;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FunnyranksMaxmindCountry extends SchemaImpl {

    private static final long serialVersionUID = -1561770730;

    /**
     * The reference instance of <code>funnyranks_maxmind_country</code>
     */
    public static final FunnyranksMaxmindCountry FUNNYRANKS_MAXMIND_COUNTRY = new FunnyranksMaxmindCountry();

    /**
     * The table <code>funnyranks_maxmind_country.country</code>.
     */
    public final Country COUNTRY = com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Country.COUNTRY;

    /**
     * The table <code>funnyranks_maxmind_country.ipv4</code>.
     */
    public final Ipv4 IPV4 = com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Ipv4.IPV4;

    /**
     * No further instances allowed
     */
    private FunnyranksMaxmindCountry() {
        super("funnyranks_maxmind_country", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Country.COUNTRY,
            Ipv4.IPV4);
    }
}
