/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country;


import com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Country;
import com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Ipv4;


/**
 * Convenience access to all tables in funnyranks_maxmind_country
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>funnyranks_maxmind_country.country</code>.
     */
    public static final Country COUNTRY = com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Country.COUNTRY;

    /**
     * The table <code>funnyranks_maxmind_country.ipv4</code>.
     */
    public static final Ipv4 IPV4 = com.github.mbto.funnyranks.common.model.funnyranks_maxmind_country.tables.Ipv4.IPV4;
}
